FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties :
        id:
            expose: true
            groups:
                - manager
        username:
            expose: true
            groups:
                - manager
        roles:
            expose: true
            groups:
                - manager
        email:
            expose: true
            groups:
                - manager
        locked:
            expose: true
            groups:
                - manager