version: '3'

volumes:
  rdb:
  nrdb:
  blockchain:
  logs:

services:
  api:
    user: ${UID:-1000}:${UID:-1000}
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    environment:
      - APP_API_DOMAIN=http://localhost:8000
    volumes:
      - ../../:/api
    ports:
      - 8000:8000

  docs:
    build: ../../docs
    environment:
      - NAME=REC
      - FAVICON_PATH=xxx
      - LOGO_HEADER_PATH=https://rec.barcelona/wp-content/uploads/2018/04/Group-3116@2x.png
      - BG_URL=https://rec.barcelona/wp-content/uploads/2018/04/Slide_home_REC_WEB.jpg
      - DOMAIN=rec.local
      - API_DOMAIN=api.rec.local
      - API_URL=http://api.rec.local
      - WIKI_URL=http://wiki.rec.local
    ports:
      - 8001:80

  rdb:
    image: mariadb
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - rdb:/var/lib/mysql

  rdbadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=rdb
      - PMA_port=3306
    ports:
      - 8080:80

  nrdb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app
      - MONGO_INITDB_ROOT_PASSWORD=app
    volumes:
      - nrdb:/var/lib/mongodb

  nrdbadmin:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=app
      - ME_CONFIG_MONGODB_ADMINPASSWORD=app
      - ME_CONFIG_MONGODB_SERVER=nrdb
    depends_on:
      - nrdb

  node:
    image: qbitartifacts/crea-node
    volumes:
      - blockchain:/root/.creativecoin
