<?php

declare(strict_types=1);

namespace App\FinancialApiBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220531073032 extends AbstractMigration
{
    public function getDescription() : string
    {
        return 'Add group_name';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE Badge ADD group_name VARCHAR(255) DEFAULT NULL, ADD group_name_es VARCHAR(255) DEFAULT NULL, ADD group_name_ca VARCHAR(255) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3F31671977792576 ON Badge (group_name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3F316719D8710211 ON Badge (group_name_es)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3F3167197D92D4DF ON Badge (group_name_ca)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP INDEX UNIQ_3F31671977792576 ON Badge');
        $this->addSql('DROP INDEX UNIQ_3F316719D8710211 ON Badge');
        $this->addSql('DROP INDEX UNIQ_3F3167197D92D4DF ON Badge');
        $this->addSql('ALTER TABLE Badge DROP group_name, DROP group_name_es, DROP group_name_ca');
    }

    public function postUp(Schema $schema): void
    {
        $this->insertConfigurationSettings('app', 'map_badges_filter_status', 'disabled');
        parent::postUp($schema); // TODO: Change the autogenerated stub
    }

    public function insertConfigurationSettings($scope, $name, $value){
        $date = new \DateTime();
        $this->connection->insert('ConfigurationSetting', array(
            'name' => $name,
            'scope' => $scope,
            'value' => $value,
            'created' => $date->format('Y-m-d H:i:s'),
            'updated' => $date->format('Y-m-d H:i:s')
        ));
    }
}
