
nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['Origin', 'Content-Type', 'Accept', 'Authorization', 'X-Signature', 'Accept-Encoding', 'Accept-Language' ]
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS', 'HEAD']
            max_age: 3600

