twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        landing_domain: '%landing_domain%'
        logo_url: '%logo_url%'
        primary_color: '%primary_color%'
        secondary_color: '%secondary_color%'
