version: '3'

volumes:
  rdb:
  nrdb:
  logs:

services:
  api:
    user: ${UID:-1000}:${UID:-1000}
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/api
    ports:
      - 8000:8000

  rdb:
    image: mariadb
    environment:
      - MYSQL_DATABASE=api
      - MYSQL_USER=api
      - MYSQL_PASSWORD=api
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3307:3306

  rdbadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=rdb
      - PMA_port=3306
    ports:
      - 8080:80

  nrdb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  nrdbadmin:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=nrdb
    depends_on:
      - nrdb

  node:
    image: qbitartifacts/crea-node