<?php

/**
 * Created by PhpStorm.
 * User: lluis
 * Date: 8/19/14
 * Time: 6:33 PM
 */

namespace Telepay\FinancialApiBundle\Controller\Management\Admin;

use FOS\RestBundle\Controller\Annotations as Rest;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Telepay\FinancialApiBundle\Controller\BaseApiController;
use Telepay\FinancialApiBundle\Entity\DelegatedChange;

/**
 * Class DelegatedChangeController
 * @package Telepay\FinancialApiBundle\Controller\Management\Admin
 */
class DelegatedChangeController extends BaseApiController{

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @Rest\View
     */
    function indexAction(Request $request)
    {
        return parent::indexAction($request); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @return \Symfony\Component\HttpFoundation\Response
     * @Rest\View
     */
    protected function showAction($id)
    {
        return parent::showAction($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Symfony\Component\HttpFoundation\Response
     * @Rest\View
     */
    protected function updateAction(Request $request, $id)
    {
        return parent::updateAction($request, $id); // TODO: Change the autogenerated stub
    }


    /**
     * @param $id
     * @return \Symfony\Component\HttpFoundation\Response
     * @Rest\View
     */
    protected function deleteAction($id)
    {
        return parent::deleteAction($id); // TODO: Change the autogenerated stub
    }


    function getRepositoryName()
    {
        return "TelepayFinancialApiBundle:DelegatedChange";
    }

    function getNewEntity()
    {
        return new DelegatedChange();
    }
}