<?php

/**
 * Created by PhpStorm.
 * User: lluis
 * Date: 4/18/19
 * Time: 12:33 PM
 */

namespace Telepay\FinancialApiBundle\Controller\Management\Admin;

use FOS\RestBundle\Controller\Annotations as Rest;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Telepay\FinancialApiBundle\Controller\BaseApiController;
use Telepay\FinancialApiBundle\Entity\DelegatedChange;

/**
 * Class DelegatedChangeController
 * @package Telepay\FinancialApiBundle\Controller\Management\Admin
 */
class DelegatedChangeController extends BaseApiController{

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @Rest\View
     */
    public function indexAction(Request $request)
    {
        return parent::indexAction($request); // TODO: Change the autogenerated stub
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @Rest\View
     */
    public function createAction(Request $request)
    {
        return parent::createAction($request); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @return \Symfony\Component\HttpFoundation\Response
     * @Rest\View
     */
    public function showAction($id)
    {
        return parent::showAction($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Symfony\Component\HttpFoundation\Response
     * @Rest\View
     */
    public function updateAction(Request $request, $id)
    {
        return parent::updateAction($request, $id); // TODO: Change the autogenerated stub
    }


    /**
     * @param $id
     * @return \Symfony\Component\HttpFoundation\Response
     * @Rest\View
     */
    public function deleteAction($id)
    {
        /** @var DelegatedChange $dc */
        $dc = $this->getRepository()->find($id);
        if($dc->getStatus() === "draft")
            return parent::deleteAction($id);
        throw new HttpException(412, "Delete delegated changes only allowed when status is 'draft'");
    }


    function getRepositoryName()
    {
        return "TelepayFinancialApiBundle:DelegatedChange";
    }

    function getNewEntity()
    {
        return new DelegatedChange();
    }
}