
##################### ACCOUNT CAMPAIGNS ############################
account_campaigns_v3_index:
    path:  /{role}/v3/{object}
    defaults: { _controller: App\FinancialApiBundle\Controller\CRUD\AccountCampaignsController::indexAction }
    methods: [GET]
    requirements:
        role: "(user)"
        object: "(account_campaign|account_campaigns)"

account_campaigns_v3_search:
    path:  /{role}/v3/{object}/search
    defaults: { _controller: App\FinancialApiBundle\Controller\CRUD\AccountCampaignsController::searchAction }
    methods: [GET]
    requirements:
        role: "(user|admin)"
        object: "(account_campaign|account_campaigns)"

account_campaigns_v3_show:
    path:  /{role}/v3/{object}/{id}
    defaults: { _controller: App\FinancialApiBundle\Controller\CRUD\AccountCampaignsController::showAction }
    methods: [GET]
    requirements:
        role: "(user)"
        object: "(account_campaign|account_campaigns)"
        id: "[0-9]+"

