
##################### PACKAGES / V3 / OVERRIDES ############################
badge_v3_search:
    path:  /{role}/v3/{object}/search
    defaults: { _controller: App\FinancialApiBundle\Controller\CRUD\PackagesController::searchAction }
    methods: [GET]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"
        object: "(packages|package)"

badges_v3_index:
    path:  /{role}/v3/{object}
    defaults: { _controller: App\FinancialApiBundle\Controller\CRUD\PackagesController::indexAction }
    methods: [GET]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"
        object: "(packages|package)"

badge_v3_show:
    path:  /{role}/v3/{object}/{id}
    defaults: { _controller: App\FinancialApiBundle\Controller\CRUD\PackagesController::showAction }
    methods: [GET]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"
        object: "(packages|package)"
        id: "[0-9]+"

badges_v3_export:
    path:  /{role}/v3/{object}/export
    defaults: { _controller: App\FinancialApiBundle\Controller\CRUD\PackagesController::exportAction }
    methods: [GET]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"
        object: "(packages|package)"

badges_v3_create:
    path:  /{role}/v3/{object}
    defaults: { _controller: App\FinancialApiBundle\Controller\CRUD\PackagesController::createAction }
    methods: [POST]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"
        object: "(packages|package)"

badge_v3_delete:
    path:  /{role}/v3/{object}/{id}
    defaults: { _controller: App\FinancialApiBundle\Controller\CRUD\PackagesController::deleteAction }
    methods: [DELETE]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"
        object: "(packages|package)"
        id: "[0-9]+"

badge_v3_update:
    path:  /{role}/v3/{object}/{id}
    defaults: { _controller: App\FinancialApiBundle\Controller\CRUD\PackagesController::updateAction }
    methods: [PUT]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"
        object: "(packages|package)"
        id: "[0-9]+"
