
##################### PACKAGES / V3 / OVERRIDES ############################
badge_v3_search:
    path:  /{role}/v3/{object}/search
    defaults: { _controller: App\FinancialApiBundle\Controller\CRUD\PackagesController::searchAction }
    methods: [GET]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"
        object: "packages"

badges_v3_index:
    path:  /{role}/v3/{object}
    defaults: { _controller: App\FinancialApiBundle\Controller\CRUD\PackagesController::indexAction }
    methods: [GET]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"
        object: "packages"

badge_v3_show:
    path:  /{role}/v3/{object}/{id}
    defaults: { _controller: App\FinancialApiBundle\Controller\CRUD\PackagesController::showAction }
    methods: [GET]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"
        object: "packages"
        id: "[0-9]+"

badges_v3_export:
    path:  /{role}/v3/{object}/export
    defaults: { _controller: App\FinancialApiBundle\Controller\CRUD\PackagesController::exportAction }
    methods: [GET]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"
        object: "packages"
