

super_admin_transaction_list:
    path:  /admin/v1/transaction/list
    defaults: { _controller: App\Controller\Management\Admin\TransactionsController::listAction }
    methods: [GET]

super_admin_transactions:
    path:  /admin/v3/transactions
    defaults: { _controller: App\Controller\Management\Admin\TransactionsController::listActionV3 }
    methods: [GET]

super_admin_transaction_refund:
    path:  /admin/v3/transaction/refund
    defaults: { _controller: App\Controller\Management\Admin\TransactionsController::createRefundFromAdmin }
    methods: [POST]

super_admin_transaction_search:
    path:  /admin/v1/transaction/{id}
    defaults: { _controller: App\Controller\Management\Admin\TransactionsController::findAction }
    methods: [GET]

super_admin_transaction_update:
    path:  /admin/v1/transaction/{id}
    defaults: { _controller: App\Controller\Management\Admin\TransactionsController::updateAction }
    methods: [PUT]

system_last50transactions_index:
    path:  /system/v1/last50
    defaults: { _controller: App\Controller\Management\System\ActivityController::last50Transactions }
    methods: [GET]


admin_companies_super_update:
    path:  /admin/v1/companies/{id}
    defaults: { _controller: App\Controller\Management\Admin\CompaniesController::updateAction }
    methods: [PUT]

admin_companies_super_delete:
    path:  /admin/v1/companies/{id}
    defaults: { _controller: App\Controller\Management\Admin\CompaniesController::deleteAction }
    methods: [DELETE]

admin_company_read:
    path:  /admin/v1/company/{id}/read
    defaults: { _controller: App\Controller\Management\Admin\CompaniesController::showAction }
    methods: [GET]

####################  USERS CAMPAIGNS  ########################
admin_users_by_campaign:
    path: /admin/v1/campaign/{id}/users
    defaults: { _controller: App\Controller\Management\Admin\CampaignsController::listUsersByCampaign }
    methods: [ GET ]

admin_export_users_by_campaign:
    path: /admin/v1/campaign/{id}/users/export
    defaults: { _controller: App\Controller\Management\Admin\CampaignsController::exportUsersByCampaign }
    methods: [ GET ]

####################  USER  ########################
admin_user_read:
    path:  /admin/v1/user/{id}
    defaults: { _controller: App\Controller\Management\Admin\UsersController::showAction }
    methods: [GET]

admin_users_update:
    path:  /admin/v1/users/{id}
    defaults: { _controller: App\Controller\Management\Admin\UsersController::updateAction }
    methods: [PUT]
    requirements:
        id: "[0-9]+"
        name: "string"
        email: "email"
        password: "string"

admin_user_active:
    path:  /admin/v1/activeuser/{id}
    defaults: { _controller: App\Controller\Management\Admin\UsersController::activateAction, _format: ~ }
    methods: [POST]
    requirements:
        id: "[0-9]+"

admin_user_deactive:
    path:  /admin/v1/deactiveuser/{id}
    defaults: { _controller: App\Controller\Management\Admin\UsersController::deactivateAction, _format: ~ }
    methods: [POST]
    requirements:
        id: "[0-9]+"

admin_users_delete:
    path:  /admin/v1/users/{id}
    defaults: { _controller: App\Controller\Management\Admin\UsersController::deleteAction, _format: ~ }
    methods: [DELETE]
    requirements:
        id: "[0-9]+"

admin_users_delete_by_name:
    path:  /admin/v1/users/name/{username}
    defaults: { _controller: App\Controller\Management\Admin\UsersController::deleteByNameAction, _format: ~ }
    methods: [DELETE]
    requirements:
        username: "string"

admin_user_update_kyc:
    path:  /admin/v1/user/{id}/kyc
    defaults: { _controller: App\Controller\Management\Admin\UsersController::updateKYCAction }
    methods: [PUT]

admin_user_update_phone:
    path:  /admin/v1/user/{id}/phone
    defaults: { _controller: App\Controller\Management\Admin\UsersController::updatePhoneAction }
    methods: [PUT]

admin_user_actions:
    path:  /admin/v1/user/{id}/{action}
    defaults: { _controller: App\Controller\Management\Admin\UsersController::userActionsAction }
    methods: [PUT]

admin_groups_delete_users:
    path:  /admin/v1/groups/{group_id}/{user_id}
    defaults: { _controller: App\Controller\Management\Admin\UsersController::deleteFromGroupAction, _format: ~ }
    methods: [DELETE]
    requirements:
        group_id: "[0-9]+"
        user_id: "[0-9]+"

##################### MAP ############################

map_visibility:
    path:  /admin/v1/map/visibility/{account_id}
    defaults: {_controller: App\Controller\Management\Admin\MapController::setVisibility }
    methods: [PUT]

admin_kyc_get_uploaded_files_by_user:
    path:  /admin/v1/kyc/uploads/{id}
    defaults: { _controller: App\Controller\Management\Admin\KYCController::getUploadedFiles }
    methods: [GET]

admin_kyc_upload_file:
    path:  /admin/v1/kyc/file/{tag}/{id}
    defaults: { _controller: App\Controller\Management\Admin\KYCController::uploadFile }
    methods: [POST]

admin_kyc_delete_file:
    path:  /admin/v1/kyc/file/{tag}/{id}
    defaults: { _controller: App\Controller\Management\Admin\KYCController::deleteFile }
    methods: [DELETE]


admin_kyc_lemon_create_account:
    path:  /admin/v1/kyc/lemon/{id}
    defaults: { _controller: App\Controller\Management\Admin\KYCController::createLemonAccountAction }
    methods: [POST]

admin_kyc_lemon_upload_files:
    path:  /admin/v1/kyc/{account_id}/lemon/upload
    defaults: { _controller: App\Controller\Management\Admin\KYCController::uploadLemonDocumentationAction }
    methods: [POST]

admin_kyc_lemon_new_id_account:
    path:  /admin/v1/kyc/lemon_id
    defaults: { _controller: App\Controller\Management\Admin\KYCController::newLemonIdAction }
    methods: [POST]



##################### ADMIN / DELEGATE CHANGE ############################

admin_index_delegate_change:
    path:  /admin/v1/delegated_changes
    defaults: { _controller: App\Controller\Management\Admin\DelegatedChangeController::indexAction }
    methods: [GET]

admin_create_delegate_change:
    path:  /admin/v1/delegated_changes
    defaults: { _controller: App\Controller\Management\Admin\DelegatedChangeController::createAction }
    methods: [POST]

admin_show_delegate_change:
    path:  /admin/v1/delegated_changes/{id}
    defaults: { _controller: App\Controller\Management\Admin\DelegatedChangeController::showAction }
    methods: [GET]

admin_update_delegate_change:
    path:  /admin/v1/delegated_changes/{id}
    defaults: { _controller: App\Controller\Management\Admin\DelegatedChangeController::updateAction }
    methods: [PUT]

admin_delete_delegate_change:
    path:  /admin/v1/delegated_changes/{id}
    defaults: { _controller: App\Controller\Management\Admin\DelegatedChangeController::deleteAction }
    methods: [DELETE]


##################### ADMIN / DELEGATE CHANGE DATA ############################

admin_index_delegate_change_data:
    path:  /admin/v1/delegated_change_data
    defaults: { _controller: App\Controller\Management\Admin\DelegatedChangeDataController::indexAction }
    methods: [GET]

admin_create_delegate_change_data:
    path:  /admin/v1/delegated_change_data
    defaults: { _controller: App\Controller\Management\Admin\DelegatedChangeDataController::createAction }
    methods: [POST]

admin_show_delegate_change_data:
    path:  /admin/v1/delegated_change_data/{id}
    defaults: { _controller: App\Controller\Management\Admin\DelegatedChangeDataController::showAction }
    methods: [GET]

admin_update_delegate_change_data:
    path:  /admin/v1/delegated_change_data/{id}
    defaults: { _controller: App\Controller\Management\Admin\DelegatedChangeDataController::updateAction }
    methods: [PUT]

admin_delete_delegate_change_data:
    path:  /admin/v1/delegated_change_data/{id}
    defaults: { _controller: App\Controller\Management\Admin\DelegatedChangeDataController::deleteAction }
    methods: [DELETE]

admin_import_csv:
    path:  /admin/v1/txs_block/csv
    defaults: { _controller: App\Controller\Management\Admin\DelegatedChangeDataController::importAction }
    methods: [POST]

admin_search_activities:
    path: /admin/v4/activities/search
    defaults: { _controller: App\Controller\Management\Company\ActivityController::searchAdminActivitiesV4 }
    methods: [ GET ]

########################## SYSTEM ############################
system_get_load:
    path:  /system/v1/load
    defaults: { _controller: App\Controller\Management\System\SystemController::load }
    methods: [GET]

system_get_cores:
    path:  /system/v1/cores
    defaults: { _controller: App\Controller\Management\System\SystemController::cores }
    methods: [GET]

system_get_memory:
    path:  /system/v1/mem
    defaults: { _controller: App\Controller\Management\System\SystemController::mem }
    methods: [GET]

system_get_net:
    path:  /system/v1/net
    defaults: { _controller: App\Controller\Management\System\SystemController::net }
    methods: [GET]

admin_nft_create_wallet:
    path:  /admin/v4/nft_wallet/{account_id}
    defaults: { _controller: App\Controller\Management\Admin\NFTController::createWallet }
    methods: [POST]
