imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@FinancialApiBundle/Resources/config/services.yml" }
    - { resource: "@FinancialApiBundle/Resources/config/validators.yml" }
    - { resource: "@FinancialApiBundle/Resources/config/app_services.yml" }
    - { resource: "@FinancialApiBundle/Resources/config/app_commons.yml" }
    - { resource: "@FinancialApiBundle/Resources/config/app_providers.yml" }
    - { resource: "@FinancialApiBundle/Resources/config/app_drivers.yml" }
    - { resource: "@FinancialApiBundle/Resources/config/app_tickers.yml" }
    - { resource: "@FinancialApiBundle/Resources/config/app_wallets.yml" }
    - { resource: "@FinancialApiBundle/Resources/config/app_money_ways.yml" }
    - { resource: "@FinancialApiBundle/Resources/config/app_exchanges.yml" }
    - { resource: "@FinancialApiBundle/Resources/config/app_config.yml" }


framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    #exception_controller: FOS\RestBundle\Controller\ExceptionController::showAction
    #exception_controller: App\FinancialApiBundle\Exception\ExceptionController::showAction

monolog:
    handlers:
        error:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%-error.log"
            level: error
        custom:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%-debug.log"
            level: debug

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: 'mariadb-10.4.8'
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                repository_factory: App\FinancialApiBundle\DependencyInjection\App\Factories\AppRepositoryFactory
                default_repository_class: App\FinancialApiBundle\Repository\AppRepository
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # (optional) it will default to the name set for the mapping
                        is_bundle: false

stof_doctrine_extensions:
  default_locale: en_US
  orm:
      default:
          tree: true
          timestampable: true
          translatable: false
          uploadable: false # not needed: listeners are not enabled by default

doctrine_migrations:
    dir_name: "%kernel.root_dir%/../src/FinancialApiBundle/Migrations"
    namespace: App\FinancialApiBundle\Migrations
    table_name: migration_versions
    name: App Migrations
    organize_migrations: false # Version >=1.2 Possible values are: "BY_YEAR", "BY_YEAR_AND_MONTH", false


# Swiftmailer Configuration
swiftmailer:
    default_mailer: first_mailer
    mailers:
        first_mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            auth_mode: login
            encryption: tls
            spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: App\FinancialApiBundle\Entity\User
    group:
      group_class: App\FinancialApiBundle\Entity\Group
    from_email:
        address: '%no_reply_email%'
        sender_name: 'No Reply'

nelmio_cors:
   defaults:
       allow_credentials: true
       allow_origin: []
       allow_headers: []
       allow_methods: []
       expose_headers: []
       max_age: 0
       hosts: []
   paths:
    '^/':
        allow_origin: ['*']
        allow_headers: ['Origin', 'Content-Type', 'Accept', 'Authorization', 'X-Signature', 'Accept-Encoding', 'Accept-Language' ]
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS', 'HEAD']
        max_age: 3600

fos_rest:
    access_denied_listener:
        json: true
        xml: true

    format_listener:
        rules:
            - { priorities: [json, xml], fallback_format: json }

    exception:
        enabled: true
        exception_controller: App\FinancialApiBundle\Exception\ExceptionController::showAction
        codes:
            App\FinancialApiBundle\Exception\PreconditionFailedException: 412
            App\FinancialApiBundle\Exception\AppLogicException: 400
        messages:
            Symfony\Component\HttpKernel\Exception\HttpException: true
            App\FinancialApiBundle\Exception\AppLogicException: true

jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUserBundle"
    visitors:
        json:
            options: JSON_UNESCAPED_SLASHES


fos_oauth_server:
    db_driver:           orm
    client_class:        App\FinancialApiBundle\Entity\Client
    access_token_class:  App\FinancialApiBundle\Entity\AccessToken
    refresh_token_class: App\FinancialApiBundle\Entity\RefreshToken
    auth_code_class:     App\FinancialApiBundle\Entity\AuthCode
    service:
        user_provider: access_key.security.user_provider
        options:
            supported_scopes: panel

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }

doctrine_mongodb:
    connections:
        default:
            server: '%mongodb_server%'
            options:
                username: '%mongodb_user%'
                password: '%mongodb_password%'
    default_database: '%mongodb_db%'
    document_managers:
        default:
            auto_mapping: true

knp_snappy:
    pdf:
        enabled:    true
        binary:     '%kernel.root_dir%/../vendor/bin/wkhtmltopdf-amd64'
        options:    []
    image:
        enabled:    true
        binary:     '%kernel.root_dir%/../vendor/bin/wkhtmltoimage-amd64'
        options:    []

services:
    _defaults:
        autowire: true # Automatically injects dependencies in your services
        autoconfigure: true
        public: false
        bind:
        # Nice feature here. Local Binding. Read about it at documentation.

    # makes classes available to be used as services
    App\:
        resource: '../../src/*'
        # exclude directories || files (if service is unused, it will be removed anyway)
        exclude: '../../src/FinancialApiBundle/{Entity,Document,Repository}'

    App\FinancialApiBundle\Controller\:
        resource: '../../src/FinancialApiBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    App\FinancialApiBundle\EventSubscriber\Doctrine\:
      resource: '../../src/FinancialApiBundle/EventSubscriber/Doctrine'
      public: true
      tags: ['doctrine.event_subscriber']

    App\FinancialApiBundle\EventSubscriber\Kernel\:
      resource: '../../src/FinancialApiBundle/EventSubscriber/Kernel'
      public: true
      tags: ['kernel.event_subscriber']

    fos_user.doctrine_registry:
        alias: doctrine

