imports:
    - { resource: config.yml }


parameters:
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    mongodb_server: 'mongodb://localhost:27017'
    mongodb_db: telepay_api_sandbox
    version: 0.9
    build_id: '#22'

    bitcoind_user: bitcoinrpc
    bitcoind_pass: 5WGq8FxFQJzsq1GTCd7seDuDwLc6rUyTZsXw4jg1H8ko
    bitcoind_host: test.chip-chap.com
    bitcoind_port: 18332

    faircoind_user: faircoinrpc
    faircoind_pass: 6kXJpCPPT2gc1J9rKipfjpGjFQ5Zb5tE2aq2LEQnencD
    faircoind_host: test.chip-chap.com
    faircoind_port: 18392

    halcash_user: fake
    halcash_pass: fake
    halcash_alias: fake

    sabadell_url_tpvv: "https://sis-t.redsys.es:25443/sis/realizarPago"
    sabadell_secret: qwertyasdf0123456789
    sabadell_name: Telepay
    sabadell_code: 327714929
    sabadell_currency: 978
    sabadell_transaction_type: 0
    sabadell_terminal: 1
    sabadell_base_url: "/test"

    paynet_reference_issuer: "467accc5-4051-4472-bb17-dad1f68779bf"

    multiva_comcurrency: 484
    multiva_comaddress: PROSA
    multiva_commerchant: 7531853
    multiva_comstore: 1234
    multiva_comterm: 001
    multiva_base_url: "/test"

    pademobile_client: 299249
    pademobile_url : 'https://staging.pademobile.com:700/comprar'
    pademobile_env_url: "/test"

    pagofacil_id_sucursal: 42ee3b415f4cebd37dffe881b929c0a0bac8a72c
    pagofacil_id_usuario: 12a27c9c912ec6b4175c3bb316365965a19f6d31
    pagofacil_id_servicio: 3
    pagofacil_url_flag: test

    safetypay_api_key: 247acc3167b49419634fe3b87e8623ef
    safetypay_signature_key: 43b4da81e4a4fc2a1c1f1b45d53bf577
    safetypay_merchant_reference: 5339
    safetypay_language: ES
    safetypay_tracking_code: ""
    safetypay_expiration_time: 5
    safetypay_response_format: CSV
    safetypay_url: "https://mws2.safetypay.com/Sandbox/express/post/v.2.2/CreateExpressToken.aspx"

    tc_contract_id: 2801
    tc_branch_id: test
    tc_url_flag: 0

    psc_username: psc_telepay_test
    psc_password: bJnAWBTUlAelk
    psc_env_url: "/test"

    ukash_generate_username: "UKASH_Telepay"
    ukash_generate_password: gdf58a4rtdut5tdy
    ukash_generate_brand_id: UKASH17740
    ukash_generate_production_flag: 0

    ukash_redemption_username: "UKASH_Hipodromo"
    ukash_redemption_password: 2eZLGxWuP9NhQOIN
    ukash_redemption_brand_id: UKASH19450
    ukash_redemption_production_flag: 0


