imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver: pdo_sqlite
        url: 'sqlite::%kernel.root_dir%/../var/db/test.sqlite'
        charset: UTF8

    orm:
        entity_managers:
            default:
                dql:
                    datetime_functions:
                        DAY: DoctrineExtensions\Query\Sqlite\Day
                        MONTH: DoctrineExtensions\Query\Sqlite\Month
                        YEAR: DoctrineExtensions\Query\Sqlite\Year
                        DATE: DoctrineExtensions\Query\Sqlite\Date
                        MINUTE: DoctrineExtensions\Query\Sqlite\Minute
                        HOUR: DoctrineExtensions\Query\Sqlite\Hour

doctrine_mongodb:
    connections:
        default:
            server: 'localhost'
    default_database: 'app'
    document_managers:
        default:
            auto_mapping: true
