imports:
    - { resource: config.yml }


parameters:
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    mongodb_server: 'mongodb://localhost:27017'
    mongodb_db: telepay_api_sandbox
    version: 0.9
    build_id: '#22'

    bitcoind_user: bitcoinrpc
    bitcoind_pass: 5WGq8FxFQJzsq1GTCd7seDuDwLc6rUyTZsXw4jg1H8ko
    bitcoind_host: test.chip-chap.com
    bitcoind_port: 18332

    faircoind_user: faircoinrpc
    faircoind_pass: 6kXJpCPPT2gc1J9rKipfjpGjFQ5Zb5tE2aq2LEQnencD
    faircoind_host: test.chip-chap.com
    faircoind_port: 18392

    halcash_user: fake
    halcash_pass: fake
    halcash_alias: fake

    sabadell_url_tpvv: "https://sis-t.redsys.es:25443/sis/realizarPago"
    sabadell_secret: qwertyasdf0123456789
    sabadell_name: Telepay
    sabadell_code: 327714929
    sabadell_currency: 978
    sabadell_transaction_type: 0
    sabadell_terminal: 1
    sabadell_base_url: "/test"

    paynet_reference_issuer: "467accc5-4051-4472-bb17-dad1f68779bf"

    multiva_comcurrency: 484
    multiva_comaddress: PROSA
    multiva_commerchant: 7531853
    multiva_comstore: 1234
    multiva_comterm: 001
    multiva_base_url: "/test"


