arbaf_financial_api:
    resource: "@ArbafFinancialApiBundle/Resources/config/routing.yml"
    host:     api.arbafinternational.com
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    host:     dev.arbafinternational.com
    prefix:   /financial

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
