
telepay_financial_api:
    resource: "@TelepayFinancialApiBundle/Resources/config/routing.yml"
    prefix:   /

telepay_login_2FA:
    path:  /oauth/v3/token
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Login2faController::loginAction }
    methods: [POST]

telepay_login_public:
    path:  /oauth/v1/public
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Login2faController::publicAction }
    methods: [POST]

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
