arbaf_financial_api:
    resource: "@ArbafFinancialApiBundle/Resources/config/routing.yml"
    host:     api.arbafinternational.com
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    host:     dev.arbafinternational.com
    prefix:   /financial
