
telepay_financial_api:
    resource: "@TelepayFinancialApiBundle/Resources/config/routing.yml"
    prefix:   /

telepay_login_2FA:
    pattern:  /oauth/v3/token
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Login2faController::loginAction }
    requirements:
        _method: POST

telepay_login_public:
    pattern:  /oauth/v1/public
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Login2faController::publicAction }
    requirements:
        _method: POST

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
