
app_financial_api:
    resource: "@FinancialApiBundle/Resources/config/routing.yml"
    prefix:   /

app_login_2FA:
    path:  /oauth/v3/token
    defaults: { _controller: App\FinancialApiBundle\Controller\Login2faController::loginAction }
    methods: [POST]

app_login_public:
    path:  /oauth/v1/public
    defaults: { _controller: App\FinancialApiBundle\Controller\Login2faController::publicAction }
    methods: [POST]

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
