security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:           ROLE_USER
        ROLE_SUPER_ADMIN:     ROLE_ADMIN

    providers:
        arbaf_financial_api:
            id: api.security.user_provider

    firewalls:

        oauth_token:
            pattern:        ^/oauth/v2/token
            security:       false

        oauth_authorize:
            pattern:        ^/oauth/v2/auth
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login
            anonymous: true

        panel:
            pattern:    ^/(admin|manager|user)/
            host:       api.arbafinternational.com
            fos_oauth:  true
            stateless:  true
            anonymous:  false


        api_test_plain:
            pattern:    ^/test/auth/ip$
            host:       api.arbafinternational.com
            stateless:  true
            security:   false

        charge2k_exception:
            pattern:    ^/services/netpay/pos/
            host:       api.arbafinternational.com
            stateless:  true
            security:   false

        api:
            pattern:    ^/services
            host:       api.arbafinternational.com
            stateless:  true
            api_arbaf:  true

        doc:
            pattern:    ^/
            host:       dev.arbafinternational.com
            security:   false

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

    access_control:
        - { host: api.arbafinternational.com, path: ^/admin/*, role: ROLE_SUPER_ADMIN }

        - { host: api.arbafinternational.com, path: ^/manager/*, role: ROLE_ADMIN }

        - { host: api.arbafinternational.com, path: ^/user/*, role: ROLE_USER }

        - { host: api.arbafinternational.com, path: ^/services/test/*, role: ROLE_SERVICES_TEST }

        - { host: api.arbafinternational.com, path: ^/services/netpay/pos/*, role: ROLE_SERVICES_NETPAY_POS }
        - { host: api.arbafinternational.com, path: ^/services/paynet/*, role: ROLE_SERVICES_PAYNET }
        - { host: api.arbafinternational.com, path: ^/services/recargafon/*, role: ROLE_SERVICES_RECARGAFON }
