security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_COMMERCE:        ROLE_USER
        ROLE_INTEGRATOR:      ROLE_COMMERCE
        ROLE_ADMIN:           ROLE_INTEGRATOR
        ROLE_SUPER_ADMIN:     ROLE_ADMIN

    providers:
        by_access_key:
            id: access_key.security.user_provider

    firewalls:

        oauth_token:
            pattern:        ^/oauth/v2/token
            security:       false

        oauth_authorize:
            pattern:        ^/oauth/v2/auth
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login
            anonymous: true

        notifications:
            pattern:    ^/notifications
            stateless:  true
            security:   false

        services:
            pattern: ^/services
            stateless: true
            fos_oauth:  true
            signature_auth: true
            switch_user:  { role: ROLE_ADMIN, parameter: su }

        oauth:
            pattern:    ^/
            fos_oauth:  true
            stateless:  true
            anonymous:  false
            switch_user:  { role: ROLE_ADMIN, parameter: su }

        default:
            anonymous: ~

    access_control:
        - { path: ^/admin/v[0-9]+/*, role: ROLE_SUPER_ADMIN }
        - { path: ^/manager/v[0-9]+/*, role: ROLE_ADMIN }
        - { path: ^/services/v[0-9]+/*, role: ROLE_INTEGRATOR }
        - { path: ^/pos/v[0-9]+/*, role: ROLE_COMMERCE }
        - { path: ^/user/v[0-9]+/*, role: ROLE_USER }


