security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_API_ADMIN:       ROLE_USER
        ROLE_API_SUPER_ADMIN: ROLE_API_ADMIN

    providers:
        arbaf_financial_api:
            id: api.security.user_provider

    firewalls:

        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

        oauth_authorize:
            pattern: ^/oauth/v2/auth
            security: false

        management_zone:
            pattern:    ^/manage
            fos_oauth:  true
            stateless:  true
            anonymous:  false

        api_test_plain:
            pattern: ^/test/auth/ip$
            host: api.arbafinternational.com
            stateless: true
            security: false

        charge2k_exception:
            pattern: ^/services/netpay/pos/
            host: api.arbafinternational.com
            stateless: true
            security: false

        api_arbaf:
            pattern: ^/
            host: api.arbafinternational.com
            stateless: true
            api_arbaf: true

        doc:
            pattern: ^/
            host: dev.arbafinternational.com
            security: false

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

    access_control:
        - { host: api.arbafinternational.com, path: ^/manage/clients/*, role: ROLE_API_SUPER_ADMIN }
        - { host: api.arbafinternational.com, path: ^/manage/groups/*, role: ROLE_API_SUPER_ADMIN }

        - { host: api.arbafinternational.com, path: ^/manage/users/*, role: ROLE_API_ADMIN }

        - { host: api.arbafinternational.com, path: ^/services/test/*, role: ROLE_API_SERVICES_TEST }
        - { host: api.arbafinternational.com, path: ^/services/netpay/pos/*, role: ROLE_API_SERVICES_NETPAY_POS }

        - { host: api.arbafinternational.com, path: ^/services/paynet/*, role: ROLE_API_SERVICES_PAYNET }
        - { host: api.arbafinternational.com, path: ^/services/recargafon/*, role: ROLE_API_SERVICES_RECARGAFON }
