security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_API_ADMIN:       ROLE_USER
        ROLE_API_SUPER_ADMIN: ROLE_API_ADMIN

    providers:
        arbaf_financial_api:
            id: api.security.user_provider

    firewalls:

        api_test_plain:
            pattern: ^/test/plain$
            host: api.arbafinternational.com
            security: false

        charge2k_exception:
            pattern: ^/services/netpay/pos/
            host: api.arbafinternational.com
            security: false

        api_arbaf:
            pattern: ^/
            host: api.arbafinternational.com
            stateless: true
            api_arbaf: true

        doc:
            pattern: ^/
            host: dev.arbafinternational.com
            security: false

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

    access_control:
        - { host: api.arbafinternational.com, path: ^/panel/*, role: ROLE_USER }

        - { host: api.arbafinternational.com, path: ^/clients/*, role: ROLE_API_SUPER_ADMIN }
        - { host: api.arbafinternational.com, path: ^/groups/*, role: ROLE_API_SUPER_ADMIN }

        - { host: api.arbafinternational.com, path: ^/users/*, role: ROLE_API_ADMIN }

        - { host: api.arbafinternational.com, path: ^/services/test/*, role: ROLE_API_SERVICES_TEST }
        - { host: api.arbafinternational.com, path: ^/services/netpay/pos/*, role: ROLE_API_SERVICES_NETPAY_POS }

        - { host: api.arbafinternational.com, path: ^/services/paynet/*, role: ROLE_API_SERVICES_PAYNET }
        - { host: api.arbafinternational.com, path: ^/services/recargafon/*, role: ROLE_API_SERVICES_RECARGAFON }
