security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        api_test:
            pattern: ^/test/plain$
            anonymous: true

        api:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

    access_control:
        - { host: api.arbafinternational.com, path: ^/clients/, role: ROLE_SUPER_ADMIN }
        - { host: api.arbafinternational.com, path: ^/users/, role: ROLE_ADMIN }
        - { host: api.arbafinternational.com, path: ^/services/, role: ROLE_USER }
