security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:           ROLE_USER
        ROLE_SUPER_ADMIN:     ROLE_ADMIN

    providers:
        by_access_key:
            id: access_key.security.user_provider

    firewalls:

        oauth_token:
            pattern:        ^/oauth/v2/token
            security:       false

        oauth_authorize:
            pattern:        ^/oauth/v2/auth
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login
            anonymous: true

        panel:
            pattern:    ^/(admin|manager|user|analytics|oauth)/
            fos_oauth:  true
            stateless:  true
            anonymous:  false
            context:    panel

        api_sandbox:
            pattern:    ^/sandbox/
            fos_oauth:  true
            stateless:  true
            anonymous:  false
            context:    panel

        charge2k_exception:
            pattern:    ^/services/netpay/pos/
            stateless:  true
            security:   false

        charge2000_test_exception:
            pattern:    ^/test/services/v1/pago/facil/
            stateless:  true
            security:   false

        charge2000_exception:
            pattern:    ^/services/v1/pago/facil/
            stateless:  true
            security:   false

        notifications_curl:
            pattern:    ^/notifications/
            stateless:  true
            security:   false

        doc:
            pattern:    ^/doc/financial
            fos_oauth:  true
            stateless:  true
            context:    panel

        api_production:
            pattern: ^/
            stateless: true
            signature_auth: true

        api_test:
            pattern: ^/test/
            stateless: true
            signature_auth: true

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

    access_control:
        - { host: path: ^/doc/financial/*, role: ROLE_USER }

        - { path: ^/admin/v[0-9]+/*, role: ROLE_SUPER_ADMIN }

        - { path: ^/manager/v[0-9]+/*, role: ROLE_ADMIN }

        - { path: ^/user/v[0-9]+/*, role: ROLE_USER }

        - { path: ^/oauth/api/v[0-9]+/*, role: ROLE_USER }

        - { path: ^/((sandbox|test|analytics|oauth)/)?services/v[0-9]+/sample/*, role: ROLE_SERVICES_SAMPLE }

        - { path: ^/((sandbox|test|analytics|oauth)/)?services/v[0-9]+/netpay/pos/*, role: ROLE_SERVICES_NETPAY_POS }
        - { path: ^/((sandbox|test|analytics|oauth)/)?services/v[0-9]+/paynet/payment/*, role: ROLE_SERVICES_PAYNET_PAYMENT }
        - { path: ^/((sandbox|test|analytics|oauth)/)?services/v[0-9]+/paynet/reference/*, role: ROLE_SERVICES_PAYNET_REFERENCE }
        - { path: ^/((sandbox|test|analytics|oauth)/)?services/v[0-9]+/recargafon/*, role: ROLE_SERVICES_RECARGAFON }
        - { path: ^/((sandbox|test|analytics|oauth)/)?services/v[0-9]+/pagofacil/*, role: ROLE_SERVICES_PAGOFACIL }
        - { path: ^/((sandbox|test|analytics|oauth)/)?services/v[0-9]+/safetypay/*, role: ROLE_SERVICES_SAFETYPAY }
        - { path: ^/((sandbox|test|analytics|oauth)/)?services/v[0-9]+/payu/*, role: ROLE_SERVICES_PAYU }
        - { path: ^/((sandbox|test|analytics|oauth)/)?services/v[0-9]+/toditocash/*, role: ROLE_SERVICES_TODITOCASH }
        - { path: ^/((sandbox|test|analytics|oauth)/)?services/v[0-9]+/ukash/generate, role: ROLE_SERVICES_UKASHGENERATE }
        - { path: ^/((sandbox|test|analytics|oauth)/)?services/v[0-9]+/ukash/payment, role: ROLE_SERVICES_UKASHPAYMENT }
        - { path: ^/((sandbox|test|analytics|oauth)/)?services/v[0-9]+/halcash/send, role: ROLE_SERVICES_HALCASHSEND }
        - { path: ^/((sandbox|test|analytics|oauth)/)?services/v[0-9]+/halcash/payment, role: ROLE_SERVICES_HALCASHPAYMENT }

