security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:            ROLE_PUBLIC
        ROLE_READONLY:        ROLE_USER
        ROLE_WORKER:          ROLE_READONLY
        ROLE_COMMERCE:        ROLE_USER
        ROLE_INTEGRATOR:      ROLE_COMMERCE
        ROLE_ADMIN:           ROLE_WORKER
        ROLE_SUPER_ADMIN:     ROLE_ADMIN

    providers:
        by_access_key:
            id: access_key.security.user_provider

    firewalls:

        oauth_token:
            pattern:        ^/oauth/v[0-9]+/token
            security:       false

        oauth_public:
            pattern:        ^/oauth/v[0-9]+/public
            security:       false

        oauth_authorize:
            pattern:        ^/oauth/v2/auth
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login
            anonymous: true

        exchange_ticker:
            pattern:    ^/exchange/v[0-9]+/(currencies|ticker)*
            stateless:  true
            security:   false

        public:
            pattern:    ^/public/*
            stateless:  true
            security:   false

        POS:
            pattern:    ^/pos/v[0-9]+/transaction/*
            stateless:  true
            security:   false

        notifications:
            pattern:    ^/notifications
            stateless:  true
            security:   false

        kyc:
            pattern:    ^/kyc/*
            stateless:  true
            security:   false

        maps:
            pattern:    ^/maps/*
            stateless:  true
            security:   false

        withdrawal:
            pattern:    ^/withdrawal/*
            stateless:  true
            security:   false

        POS_notifications:
            pattern:    ^/pos/v[0-9]+/notification/*
            stateless:  true
            security:   false

        POS_check:
            pattern:    ^/pos/v[0-9]+/check/*
            stateless:  true
            security:   false

        POS_cancel:
            pattern:    ^/pos/v[0-9]+/cancel/*
            stateless:  true
            security:   false

        services:
            pattern: ^/services
            stateless: true
            fos_oauth:  true
            signature_auth: true
            switch_user:  { role: ROLE_ADMIN, parameter: su }

        methods:
            pattern: ^/methods
            stateless: true
            fos_oauth:  true
            signature_auth: true
            switch_user:  { role: ROLE_WORKER, parameter: su }

        user:
            pattern: ^/user
            stateless: true
            fos_oauth:  true
            signature_auth: true
            switch_user:  { role: ROLE_ADMIN, parameter: su }

        swift_api:
            pattern:  ^/swift
            stateless: true
            fos_oauth:  true
            signature_auth: true
            anonymous: true

        old_api:
            pattern:  ^/api
            stateless: true
            fos_oauth:  true
            signature_auth: true
            anonymous: true

        commerce_register:
            pattern:  ^/register/v1/commerce
            stateless: true
            fos_oauth:  true
            anonymous: true

        resent_email_validation:
            pattern:  ^/register/v1/sent_validation_email
            stateless: true
            security: false

        oauth:
            pattern:    ^/
            fos_oauth:  true
            stateless:  true
            anonymous:  false
            signature_auth: true
            switch_user:  { role: ROLE_ADMIN, parameter: su }

        default:
            anonymous: ~

    access_control:
        - { path: ^/system/v[0-2]+/*, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/v[0-2]+/*, role: ROLE_SUPER_ADMIN }
        - { path: ^/manager/v[0-2]+/*, role: ROLE_ADMIN, methods: [POST,PUT,DELETE] }
        - { path: ^/company/v[0-2]+/*, role: ROLE_USER, methods: [GET] }
        - { path: ^/company/v[0-2]+/*, role: ROLE_WORKER, methods: [POST,PUT,DELETE] }
        - { path: ^/services/v[0-2]+/*, role: ROLE_ADMIN }
        - { path: ^/methods/v[0-2]+/*, role: ROLE_WORKER }

        - { path: ^/pos/v[0-2]+/transaction/*, role: IS_AUTHENTICATED_ANONYMOUSLY, ip: ["127.0.0.1"] }
        - { path: ^/pos/v[0-2]+/check/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pos/v[0-2]+/cancel/*, role: IS_AUTHENTICATED_ANONYMOUSLY, ip: ["127.0.0.1"]  }

        - { path: ^/user/v[0-2]+/pos/link/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/v[0-2]+/*, role: ROLE_USER }
        - { path: ^/self/v[0-2]+/*, role: ROLE_USER }
        - { path: ^/register/v[0-2]+, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password_recovery/v[0-2]+, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # V3+ access_control
        - { path: ^/public/v[3-9]+/*, role: ROLE_PUBLIC}
        - { path: ^/user/v[3-9]+/*, role: ROLE_USER }
        - { path: ^/manager/v[3-9]+/*, role: ROLE_MANAGER }
        - { path: ^/self/v[3-9]+/*, role: ROLE_SELF }
        - { path: ^/admin/v[3-9]+/*, role: ROLE_ADMIN }
        - { path: ^/sadmin/v[3-9]+/*, role: ROLE_SUPER_ADMIN }

