security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:           ROLE_USER
        ROLE_SUPER_ADMIN:     ROLE_ADMIN

    providers:
        by_access_key:
            id: access_key.security.user_provider

    firewalls:

        oauth_token:
            pattern:        ^/oauth/v2/token
            security:       false

        oauth_authorize:
            pattern:        ^/oauth/v2/auth
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login
            anonymous: true

        panel:
            pattern:    ^/(admin|manager|user)/
            fos_oauth:  true
            stateless:  true
            anonymous:  false
            context:    panel

        api_sandbox:
            pattern:    ^/sandbox/
            fos_oauth:  true
            stateless:  true
            anonymous:  false
            context:    panel

        charge2k_exception:
            pattern:    ^/services/netpay/pos/
            stateless:  true
            security:   false

        doc:
            pattern:    ^/doc/financial
            fos_oauth:  true
            stateless:  true
            context:    panel

        api_production:
            pattern: ^/
            stateless: true
            signature_auth: true

        api_test:
            pattern: ^/test/
            stateless: true
            signature_auth: true


        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

    access_control:
        - { host: path: ^/doc/financial/*, role: ROLE_USER, requires_channel: http }

        - { path: ^/admin/v[0-9]+/*, role: ROLE_SUPER_ADMIN, requires_channel: http }

        - { path: ^/manager/v[0-9]+/*, role: ROLE_ADMIN, requires_channel: http }

        - { path: ^/user/v[0-9]+/*, role: ROLE_USER, requires_channel: http }

        - { path: ^/((sandbox|test)/)?services/v[0-9]+/test/*, role: ROLE_USER, requires_channel: http }

        - { path: ^/((sandbox|test)/)?services/v[0-9]+/netpay/pos/*, role: ROLE_SERVICES_NETPAY_POS, requires_channel: http }
        - { path: ^/((sandbox|test)/)?services/v[0-9]+/paynet/*, role: ROLE_SERVICES_PAYNET, requires_channel: http }
        - { path: ^/((sandbox|test)/)?services/v[0-9]+/recargafon/*, role: ROLE_SERVICES_RECARGAFON, requires_channel: http }
        
