security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:           ROLE_USER
        ROLE_SUPER_ADMIN:     ROLE_ADMIN

    providers:
        by_access_key:
            id: access_key.security.user_provider

    firewalls:

        oauth_token:
            pattern:        ^/oauth/v2/token
            security:       false

        oauth_authorize:
            pattern:        ^/oauth/v2/auth
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login
            anonymous: true

        panel:
            pattern:    ^/v[0-9]+/(admin|manager|user)/
            fos_oauth:  true
            stateless:  true
            anonymous:  false
            context:    panel

        api_sandbox:
            pattern:    ^/sandbox/v[0-9]+/
            fos_oauth:  true
            stateless:  true
            anonymous:  false
            context:    panel

        charge2k_exception:
            pattern:    ^/services/netpay/pos/
            stateless:  true
            security:   false

        doc:
            pattern:    ^/financial
            host:       dev-dev.telepay.net
            security:   false
            #context:    panel

        signature_access:
            pattern: ^/v[0-9]+/
            stateless: true
            signature_auth: true

        signature_access:
            pattern: ^/test/v[0-9]+/
            stateless: true
            signature_auth: true


        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

    access_control:
        #- { host: ((pre|dev)-)?dev.telepay.net, path: ^/financial/*, role: ROLE_USER, requires_channel: http }

        - { path: ^/v[0-9]+/admin/*, role: ROLE_SUPER_ADMIN, requires_channel: http }

        - { path: ^/v[0-9]+/manager/*, role: ROLE_ADMIN, requires_channel: http }

        - { path: ^/v[0-9]+/user/*, role: ROLE_USER, requires_channel: http }

        - { path: ^/((sandbox|test)/)?v[0-9]+/services/test/*, role: ROLE_USER, requires_channel: http }

        - { path: ^/((sandbox|test)/)?v[0-9]+/services/netpay/pos/*, role: ROLE_SERVICES_NETPAY_POS, requires_channel: http }
        - { path: ^/((sandbox|test)/)?v[0-9]+/services/paynet/*, role: ROLE_SERVICES_PAYNET, requires_channel: http }
        - { path: ^/((sandbox|test)/)?v[0-9]+/services/recargafon/*, role: ROLE_SERVICES_RECARGAFON, requires_channel: http }
