
##################### ACCOUNT_ AWARDS ############################
awards_by_account:
    path: /{role}/v3/account/{id}/awards
    defaults: { _controller: App\Controller\CRUD\AccountAwardsController::indexByAccountAction }
    methods: [ GET ]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"

##################### ACCOUNT_ AWARDS_ITEMS by account ############################
award_items_by_account:
    path: /{role}/v3/account/{id}/award_items
    defaults: { _controller: App\Controller\CRUD\AwardItemsController::indexByAccountAction }
    methods: [ GET ]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"

##################### ACCOUNT_ AWARDS_ITEMS / V3 / OVERRIDES ############################
award_items_v3_search:
    path:  /{role}/v3/{object}/search
    defaults: { _controller: App\Controller\CRUD\AwardItemsController::searchAction }
    methods: [GET]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"
        object: "(account_award_item|account_award_items)"

award_items_v3_index:
    path:  /{role}/v3/{object}
    defaults: { _controller: App\Controller\CRUD\AwardItemsController::indexAction }
    methods: [GET]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"
        object: "(account_award_item|account_award_items)"

award_items_v3_show:
    path:  /{role}/v3/{object}/{id}
    defaults: { _controller: App\Controller\CRUD\AwardItemsController::showAction }
    methods: [GET]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"
        object: "(account_award_item|account_award_items)"
        id: "[0-9]+"

award_items_v3_export:
    path:  /{role}/v3/{object}/export
    defaults: { _controller: App\Controller\CRUD\AwardItemsController::exportAction }
    methods: [GET]
    requirements:
        role: "(public|user|manager|self|admin|sadmin)"
        object: "(account_award_item|account_award_items)"
