version: 2
jobs:
  build:
    branches:
      only:
        - master
        - containerize
        - stable
    machine: true
    steps:
      - checkout

      # with credentials stored in the UI
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS reg.rallf.com:8443

      # build the application image
      - run: docker build . -t reg.rallf.com:8443/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
      - run: docker build docs -t reg.rallf.com:8443/rec-dev:$CIRCLE_BRANCH

      # push the API image
      - run: docker push reg.rallf.com:8443/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
      - run: docker push reg.rallf.com:8443/rec-dev:$CIRCLE_BRANCH

      # use webhook to deploy
      - run: curl -X POST $API_DEPLOY_WEBHOOK
      - run: curl -X POST $DEV_DEPLOY_WEBHOOK
