version: 2
jobs:
  build:
    branches:
      only:
        - master
        - containerize
        - stable
    machine: true
    steps:
      - checkout

      # Docker Registry Login
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS reg.rallf.com:8443

      # Build the application images
      - run: make
      - run: docker build docs -t reg.rallf.com:8443/rec-dev:$CIRCLE_BRANCH

      # Push the API image to the Registry
      - run: make deploy
      - run: docker push reg.rallf.com:8443/rec-dev:$CIRCLE_BRANCH

      # use webhook to deploy
      - run: tr ',' '\n' <<<$DEPLOY_WEBHOOK | while read url;do curl -X POST "$url";done
