version: 2
jobs:
  build:
    branches:
      only:
        - stable
    machine: true
    steps:
      - checkout

      # docker login with credentials stored in the CI
      - run: make login DOCKER_REGISTRY=$REGISTRY DOCKER_USERNAME=$USERNAME DOCKER_PASSWORD=$PASSWORD

      # build the application image
      - run: make build DOCKER_REGISTRY=$REGISTRY DOCKER_IMAGE=rec-api DOCKER_TAG=$CIRCLE_BRANCH DOCKERFILE_DIR=docker/prod/api
      - run: make build DOCKER_REGISTRY=$REGISTRY DOCKER_IMAGE=rec-cron DOCKER_TAG=$CIRCLE_BRANCH DOCKERFILE_DIR=docker/prod/cron
      - run: make build DOCKER_REGISTRY=$REGISTRY DOCKER_IMAGE=rec-dev DOCKER_TAG=$CIRCLE_BRANCH BUILD_DIR=docs

      # push the application image to registry
      - run: make push DOCKER_REGISTRY=$REGISTRY DOCKER_IMAGE=rec-api DOCKER_TAG=$CIRCLE_BRANCH
      - run: make push DOCKER_REGISTRY=$REGISTRY DOCKER_IMAGE=rec-cron DOCKER_TAG=$CIRCLE_BRANCH
      - run: make push DOCKER_REGISTRY=$REGISTRY DOCKER_IMAGE=rec-dev DOCKER_TAG=$CIRCLE_BRANCH

      # deploy with webhook (put every url separated by comma)
      - run: make deploy WEBHOOK=$WEBHOOK
