




############################### 2000 CHARGE ############################################

services_2000charge_pagofacil_transaction:
    pattern:  /services/v1/pago/facil/transaction
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\Services2000chargePagofacilController::transaction, _format: ~ }
    requirements:
        _method: POST

services_2000charge_pagofacil_transaction_test:
    pattern:  /test/services/v1/pago/facil/transaction
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\Services2000chargePagofacilController::transactionTest, _format: ~ }
    requirements:
        _method: POST

services_2000charge_pagofacil_status:
    pattern:  /services/v1/pago/facil/status
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\Services2000chargePagofacilController::status, _format: ~ }
    requirements:
        _method: POST

services_2000charge_pagofacil_status_test:
    pattern:  /test/services/v1/pago/facil/status
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\Services2000chargePagofacilController::statusTest, _format: ~ }
    requirements:
        _method: POST
