
services_bitcoin_payment:
    pattern:  /services/v1/bitcoin/payment
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\Cryptos\Bitcoin::createPayment, _format: ~ }
    requirements:
        _method: POST

services_bitcoin_payment_sandbox:
    pattern:  /sandbox/services/v1/bitcoin/payment
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\Cryptos\Bitcoin::createPaymentTest, _format: ~ }
    requirements:
        _method: POST

services_bitcoin_payment_test:
    pattern:  /test/services/v1/bitcoin/payment
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\Cryptos\Bitcoin::createPaymentTest, _format: ~ }
    requirements:
        _method: POST


services_bitcoin_check_payment:
    pattern:  /services/v1/bitcoin/payment/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\Cryptos\Bitcoin::checkPayment, _format: ~ }
    requirements:
        _method: GET
        id: "[a-z0-9]+"

services_bitcoin_check_payment_sandbox:
    pattern:  /sandbox/services/v1/bitcoin/payment/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\Cryptos\Bitcoin::checkPaymentTest, _format: ~ }
    requirements:
        _method: GET
        id: "[a-z0-9]+"

services_bitcoin_check_payment_test:
    pattern:  /test/services/v1/bitcoin/payment/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\Cryptos\Bitcoin::checkPaymentTest, _format: ~ }
    requirements:
        _method: GET
        id: "[a-z0-9]+"

