
services_halcash_send:
    pattern:  /services/v1/halcash/send
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesHalcashController::send, _format: ~ }
    requirements:
        _method: POST

services_halcash_send_sandbox:
    pattern:  /sandbox/services/v1/halcash/send
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesHalcashController::sendTest, _format: ~ }
    requirements:
        _method: POST

services_halcash_send_test:
    pattern:  /test/services/v1/halcash/send
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesHalcashController::sendTest, _format: ~ }
    requirements:
        _method: POST

services_halcash_payment:
    pattern:  /services/v1/halcash/payment
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesHalcashController::payment, _format: ~ }
    requirements:
        _method: POST

services_halcash_payment_sandbox:
    pattern:  /sandbox/services/v1/halcash/payment
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesHalcashController::paymentTest, _format: ~ }
    requirements:
        _method: POST

services_halcash_payment_test:
    pattern:  /test/services/v1/halcash/payment
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesHalcashController::paymentTest, _format: ~ }
    requirements:
        _method: POST

######################### HALCASH SERVICE STATS ############################

analytics_halcash_send_transactions:
    pattern:  /analytics/services/v1/halcashsend/transactions
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\HalcashSendAnalytics::transactions }
    requirements:
        _method: GET

analytics_halcash_send_test_transactions:
    pattern:  /analytics/services/v1/halcashsend/transactions/test
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\HalcashSendAnalytics::transactionsTest }
    requirements:
        _method: GET

analytics_halcash_send_sum:
    pattern:  /analytics/services/v1/halcashsend/sum
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\HalcashSendAnalytics::stats }
    requirements:
        _method: GET

analytics_halcash_payment_transactions:
    pattern:  /analytics/services/v1/halcashpayment/transactions
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\HalcashPaymentAnalytics::transactions }
    requirements:
        _method: GET

analytics_halcash_payment_test_transactions:
    pattern:  /analytics/services/v1/halcashpayment/transactions/test
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\HalcashPaymentAnalytics::transactionsTest }
    requirements:
        _method: GET

analytics_halcash_payment_sum:
    pattern:  /analytics/services/v1/halcashpayment/sum
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\HalcashPaymentAnalytics::stats }
    requirements:
        _method: GET
