
services_multiva_generate:
    pattern:  /services/v1/multiva/generate
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesMultivaTPVController::generate, _format: ~ }
    requirements:
        _method: POST

services_multiva_generate_sandbox:
    pattern:  /sandbox/services/v1/multiva/generate
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesMultivaTPVController::generateTest, _format: ~ }
    requirements:
        _method: POST

services_multiva_generate_test:
    pattern:  /test/services/v1/multiva/generate
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesMultivaTPVController::generateTest, _format: ~ }
    requirements:
        _method: POST



######################### MULTIVA TPV SERVICE STATS ############################

analytics_multiva_generate_transactions:
    pattern:  /analytics/services/v1/multiva/transactions
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\MultivaAnalytics::transactions }
    requirements:
        _method: GET

analytics_multiva_generate_transactions:
    pattern:  /analytics/services/v1/multiva/transactions/test
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\MultivaAnalytics::transactionsTest }
    requirements:
        _method: GET

analytics_multiva_generate_sum:
    pattern:  /analytics/services/v1/multiva/sum
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\MultivaAnalytics::stats }
    requirements:
        _method: GET