



services_netpay_pos_register:
    pattern:  /services/v1/netpay/pos/register
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesNetpayPosController::registerAction, _format: ~ }
    requirements:
        _method: POST

services_netpay_pos_transaction:
    pattern:  /services/v1/netpay/pos/transaction
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesNetpayPosController::transactionAction, _format: ~ }
    requirements:
        _method: POST
