


services_paynet_reference_generate:
    pattern:  /services/v1/paynet/reference/generate
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPaynetReferenceController::generate, _format: ~ }
    requirements:
        _method: POST

services_paynet_reference_generate_sandbox:
    pattern:  /sandbox/services/v1/paynet/reference/generate
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPaynetReferenceController::generateTest, _format: ~ }
    requirements:
        _method: POST

services_paynet_reference_generate_test:
    pattern:  /test/services/v1/paynet/reference/generate
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPaynetReferenceController::generateTest, _format: ~ }
    requirements:
        _method: POST

services_paynet_reference_status:
    pattern:  /services/v1/paynet/reference/status
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPaynetReferenceController::status, _format: ~ }
    requirements:
        _method: POST

services_paynet_reference_status_sandbox:
    pattern:  /sandbox/services/v1/paynet/reference/status
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPaynetReferenceController::statusTest, _format: ~ }
    requirements:
        _method: POST

services_paynet_reference_status_test:
    pattern:  /test/services/v1/paynet/reference/status
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPaynetReferenceController::statusTest, _format: ~ }
    requirements:
        _method: POST








######################### PAYNET REFERENCE SERVICE STATS ############################

analytics_paynet_reference_transactions:
    pattern:  /analytics/services/v1/paynet/reference/transactions
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\PaynetReferenceAnalytics::transactions }
    requirements:
        _method: GET

analytics_paynet_payment_test_transactions:
    pattern:  /analytics/services/v1/paynet/reference/transactions/test
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\PaynetReferenceAnalytics::transactionsTest }
    requirements:
        _method: GET