###############      PAYSAFECARD REQUEST     ###################################################3

     #####     v1     #####

services_paysafecard_payment_request:
    pattern:  /services/v1/paysafecard/payment/request
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPaysafecardPaymentController::request, _format: ~ }
    requirements:
        _method: POST

services_paysafecard_payment_request_sandbox:
    pattern:  /sandbox/services/v1/paysafecard/payment/request
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPaysafecardPaymentController::requestTest, _format: ~ }
    requirements:
        _method: POST

services_paysafecard_payment_request_test:
    pattern:  /test/services/v1/paysafecard/payment/request
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPaysafecardPaymentController::requestTest, _format: ~ }
    requirements:
        _method: POST

     #####     v2     #####

services_paysafecard_payment_request_v2:
    pattern:  /services/v2/paysafecard/payment/request
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPaysafecardPaymentController::requestV2, _format: ~ }
    requirements:
        _method: POST

services_paysafecard_payment_request_sandbox_v2:
    pattern:  /sandbox/services/v2/paysafecard/payment/request
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPaysafecardPaymentController::requestTestV2, _format: ~ }
    requirements:
        _method: POST

services_paysafecard_payment_request_test_v2:
    pattern:  /test/services/v2/paysafecard/payment/request
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPaysafecardPaymentController::requestTestV2, _format: ~ }
    requirements:
        _method: POST

######################### SAFETYPAY SERVICE STATS ############################

analytics_paysafecard_transactions:
    pattern:  /analytics/services/v1/paysafecard/transactions
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\PaysafecardAnalytics::transactions }
    requirements:
        _method: GET

analytics_paysafecard_test_transactions:
    pattern:  /analytics/services/v1/paysafecard/transactions/test
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\PaysafecardAnalytics::transactionsTest }
    requirements:
        _method: GET

analytics_paysafecard_sum:
    pattern:  /analytics/services/v1/paysafecard/sum
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\PaysafecardAnalytics::stats }
    requirements:
        _method: GET
