

services_payu_payment_transaction:
    pattern:  /services/v1/payu/payment/transaction
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPayuPaymentController::transaction, _format: ~ }
    requirements:
        _method: POST

services_payu_payment_transaction_sandbox:
    pattern:  /sandbox/services/v1/payu/payment/transaction
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPayuPaymentController::transactionTest, _format: ~ }
    requirements:
        _method: POST

services_payu_payment_transaction_test:
    pattern:  /test/services/v1/payu/payment/transaction
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPayuPaymentController::transactionTest, _format: ~ }
    requirements:
        _method: POST

services_payu_payment_cash:
    pattern:  /services/v1/payu/payment/cash
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPayuPaymentController::cash, _format: ~ }
    requirements:
        _method: POST

services_payu_payment_cash_sandbox:
    pattern:  /sandbox/services/v1/payu/payment/cash
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPayuPaymentController::cashTest, _format: ~ }
    requirements:
        _method: POST

services_payu_payment_cash_test:
    pattern:  /test/services/v1/payu/payment/cash
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPayuPaymentController::cashTest, _format: ~ }
    requirements:
        _method: POST

services_payu_payment_report:
    pattern:  /services/v1/payu/payment/report
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPayuPaymentController::report, _format: ~ }
    requirements:
        _method: GET

services_payu_payment_report_sandbox:
    pattern:  /sandbox/services/v1/payu/payment/report
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPayuPaymentController::reportTest, _format: ~ }
    requirements:
        _method: GET

services_payu_payment_report_test:
    pattern:  /test/services/v1/payu/payment/report
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesPayuPaymentController::reportTest, _format: ~ }
    requirements:
        _method: GET

######################### PAYU SERVICE STATS ############################

analytics_payu_transactions:
    pattern:  /analytics/services/v1/payu/transactions
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\PayuAnalytics::transactions }
    requirements:
        _method: GET

analytics_payu_test_transactions:
    pattern:  /analytics/services/v1/payu/transactions/test
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\PayuAnalytics::transactionsTest }
    requirements:
        _method: GET

analytics_payu_sum:
    pattern:  /analytics/services/v1/payu/sum
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\PayuAnalytics::stats }
    requirements:
        _method: GET