
######################### SERVICE ############################

services_sample:
    pattern:  /services/v1/sample
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\SampleService::test }
    requirements:
        _method: GET

services_sample_sandbox:
    pattern:  /sandbox/services/v1/sample
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\SampleService::testTest }
    requirements:
        _method: GET

services_sample_test:
    pattern:  /test/services/v1/sample
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\SampleService::testTest }
    requirements:
        _method: GET


######################### ANALYTICS ############################

analytics_sample_transactions:
    pattern:  /analytics/services/v1/sample/transactions
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\SampleAnalytics::transactions }
    requirements:
        _method: GET

analytics_sample_transactions_test:
    pattern:  /analytics/services/v1/sample/transactions/test
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\SampleAnalytics::transactionsTest }
    requirements:
        _method: GET

analytics_sample_analytics:
    pattern:  /analytics/services/v1/sample/sum
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\SampleAnalytics::stats }
    requirements:
        _method: GET