

######################### ANALYTICS ############################

services_ukash_redirect_request:
    pattern:  /services/v1/ukash/redirect/request
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesUkashRedirectController::request, _format: ~ }
    requirements:
        _method: POST

services_ukash_redirect_request_sandbox:
    pattern:  /sandbox/services/v1/ukash/redirect/request
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesUkashRedirectController::requestTest, _format: ~ }
    requirements:
        _method: POST

services_ukash_redirect_request_test:
    pattern:  /test/services/v1/ukash/redirect/request
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesUkashRedirectController::requestTest, _format: ~ }
    requirements:
        _method: POST

services_ukash_redirect_status:
    pattern:  /services/v1/ukash/redirect/status
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesUkashRedirectController::status, _format: ~ }
    requirements:
        _method: GET

services_ukash_redirect_status_sandbox:
    pattern:  /sandbox/services/v1/ukash/redirect/status
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesUkashRedirectController::statusTest, _format: ~ }
    requirements:
        _method: GET

services_ukash_redirect_status_test:
    pattern:  /test/services/v1/ukash/redirect/status
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Services\ServicesUkashRedirectController::statusTest, _format: ~ }
    requirements:
        _method: GET



######################### ANALYTICS ############################

analytics_ukash_transactions:
    pattern:  /analytics/services/v1/ukash/transactions
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\UkashAnalytics::transactions }
    requirements:
        _method: GET

analytics_ukash_test_transactions:
    pattern:  /analytics/services/v1/ukash/transactions/test
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\UkashAnalytics::transactionsTest }
    requirements:
        _method: GET

analytics_ukash_sum:
    pattern:  /analytics/services/v1/ukash/sum
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Analytics\UkashAnalytics::stats }
    requirements:
        _method: GET
