services:

    net.telepay.ways:
        class: Telepay\FinancialApiBundle\Financial\ObjectRegister
        arguments:
            objects:
                - "@net.telepay.link.bittrex_fair.bittrex_btc"
                - "@net.telepay.link.bittrex_btc.bittrex_fair"
                - "@net.telepay.link.kraken_btc.kraken_eur"
                - "@net.telepay.link.kraken_eur.kraken_btc"
                - "@net.telepay.link.fullnode_btc.kraken_btc"
                - "@net.telepay.link.kraken_btc.fullnode_btc"
                - "@net.telepay.link.fullnode_fair.bittrex_fair"
                - "@net.telepay.link.bittrex_fair.fullnode_fair"
                - "@net.telepay.link.fullnode_btc.bittrex_btc"
                - "@net.telepay.link.bittrex_btc.fullnode_btc"
                - "@net.telepay.link.bittrex_btc.kraken_btc"
                - "@net.telepay.link.kraken_btc.bittrex_btc"
                - "@net.telepay.link.kraken_eur.caixacoves_eur"
                - "@net.telepay.link.caixacoves_eur.kraken_eur"

    net.telepay.link.bittrex_fair.bittrex_btc:
        class: Telepay\FinancialApiBundle\Financial\Linker\BasicLinker
        arguments:
            - "@net.telepay.wallet.bittrex.fair"
            - "@net.telepay.wallet.bittrex.btc"
            - "1000"
            - "1"
            - "0.25"

    net.telepay.link.bittrex_btc.bittrex_fair:
        class: Telepay\FinancialApiBundle\Financial\Linker\BasicLinker
        arguments:
            - "@net.telepay.wallet.bittrex.btc"
            - "@net.telepay.wallet.bittrex.fair"
            - "0.1"
            - "1"
            - "0.25"

    net.telepay.link.kraken_btc.kraken_eur:
        class: Telepay\FinancialApiBundle\Financial\Linker\BasicLinker
        arguments:
            - "@net.telepay.wallet.kraken.btc"
            - "@net.telepay.wallet.kraken.eur"
            - "0.1"
            - "1"
            - "0.25"

    net.telepay.link.kraken_eur.kraken_btc:
        class: Telepay\FinancialApiBundle\Financial\Linker\BasicLinker
        arguments:
            - "@net.telepay.wallet.kraken.eur"
            - "@net.telepay.wallet.kraken.btc"
            - "50"
            - "1"
            - "0.25"

    net.telepay.link.fullnode_btc.kraken_btc:
        class: Telepay\FinancialApiBundle\Financial\Linker\BasicLinker
        arguments:
            - "@net.telepay.wallet.fullnode.btc"
            - "@net.telepay.wallet.kraken.btc"
            - "0.1"
            - "1"
            - "0"

    net.telepay.link.kraken_btc.fullnode_btc:
        class: Telepay\FinancialApiBundle\Financial\Linker\BasicLinker
        arguments:
            - "@net.telepay.wallet.kraken.btc"
            - "@net.telepay.wallet.fullnode.btc"
            - "0.1"
            - "1"
            - "0"

    net.telepay.link.fullnode_fair.bittrex_fair:
        class: Telepay\FinancialApiBundle\Financial\Linker\BasicLinker
        arguments:
            - "@net.telepay.wallet.fullnode.fair"
            - "@net.telepay.wallet.bittrex.fair"
            - "1000"
            - "1"
            - "0"

    net.telepay.link.bittrex_fair.fullnode_fair:
        class: Telepay\FinancialApiBundle\Financial\Linker\BasicLinker
        arguments:
            - "@net.telepay.wallet.bittrex.fair"
            - "@net.telepay.wallet.fullnode.fair"
            - "1000"
            - "1"
            - "0"

    net.telepay.link.fullnode_btc.bittrex_btc:
        class: Telepay\FinancialApiBundle\Financial\Linker\BasicLinker
        arguments:
            - "@net.telepay.wallet.fullnode.btc"
            - "@net.telepay.wallet.bittrex.btc"
            - "0.1"
            - "1"
            - "0"

    net.telepay.link.bittrex_btc.fullnode_btc:
        class: Telepay\FinancialApiBundle\Financial\Linker\BasicLinker
        arguments:
            - "@net.telepay.wallet.bittrex.btc"
            - "@net.telepay.wallet.fullnode.btc"
            - "0.1"
            - "1"
            - "0"

    net.telepay.link.bittrex_btc.kraken_btc:
        class: Telepay\FinancialApiBundle\Financial\Linker\BasicLinker
        arguments:
            - "@net.telepay.wallet.bittrex.btc"
            - "@net.telepay.wallet.kraken.btc"
            - "0.1"
            - "1"
            - "0"

    net.telepay.link.kraken_btc.bittrex_btc:
        class: Telepay\FinancialApiBundle\Financial\Linker\BasicLinker
        arguments:
            - "@net.telepay.wallet.kraken.btc"
            - "@net.telepay.wallet.bittrex.btc"
            - "0.1"
            - "1"
            - "0"

    net.telepay.link.kraken_eur.caixacoves_eur:
        class: Telepay\FinancialApiBundle\Financial\Linker\BasicLinker
        arguments:
            - "@net.telepay.wallet.kraken.eur"
            - "@net.telepay.wallet.caixacoves.eur"
            - "500"
            - "1000"
            - "0.2"

    net.telepay.link.caixacoves_eur.kraken_eur:
        class: Telepay\FinancialApiBundle\Financial\Linker\BasicLinker
        arguments:
            - "@net.telepay.wallet.caixacoves.eur"
            - "@net.telepay.wallet.kraken.eur"
            - "500"
            - "1000"
            - "0"
