services:

    net.telepay.driver.provider:
        class: Telepay\FinancialApiBundle\Financial\ObjectRegister
        arguments:
            drivers:
                - "@net.telepay.driver.easybitcoin.rec"
                - "@net.telepay.driver.lemonway.eur"

    net.telepay.driver.easybitcoin.rec:
        class: Telepay\FinancialApiBundle\Financial\Driver\FakeEasyBitcoinDriverDriver
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%blockchain_address_prefix%'

    net.telepay.driver.lemonway.eur:
        class: Telepay\FinancialApiBundle\Financial\Driver\LemonWayDriver
        arguments:
            - "%lemonway_url%"
            - "%lemonway_user%"
            - "%lemonway_pass%"
            - "%lemonway_version%"
            - "%lemonway_admin_account%"
