services:

    net.telepay.ticker.RECxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\RecTicker
        arguments:
            - "REC"
            - "EUR"

    net.telepay.ticker.EURxREC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\RecTicker
        arguments:
            - "EUR"
            - "REC"
