services:

    net.telepay.trader.FACxBTC:
        class: Telepay\FinancialApiBundle\Financial\Trader\BittrexTrader
        arguments:
            - "@net.telepay.driver.bittrex"

    net.telepay.wallet.bittrex.fair:
        class: Telepay\FinancialApiBundle\Financial\Wallet\BittrexWallet
        arguments:
            - "@net.telepay.driver.bittrex"
            - "FAIR"

    net.telepay.wallet.bittrex.btc:
        class: Telepay\FinancialApiBundle\Financial\Wallet\BittrexWallet
        arguments:
            - "@net.telepay.driver.bittrex"
            - "BTC"

    net.telepay.wallet.kraken.btc:
        class: Telepay\FinancialApiBundle\Financial\Wallet\KrakenWallet
        arguments:
            - "@net.telepay.driver.kraken"
            - "BTC"

    net.telepay.driver.kraken:
        class: Payward\KrakenAPI
        arguments:
            - "%kraken_api_key%"
            - "%kraken_private_key%"

    net.telepay.driver.bittrex:
        class: Telepay\FinancialApiBundle\Financial\Driver\BittrexDriver
        arguments:
            - "%bittrex_api_url%"
            - "%bittrex_api_key%"
            - "%bittrex_api_secret%"

    net.telepay.driver.getfaircoin:
        class: GetFaircoin\Ticker

    net.telepay.ticker.FACxBTC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\BittrexTicker
        arguments:
            - "@net.telepay.driver.bittrex"

    net.telepay.ticker.BTCxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\KrakenTicker
        arguments:
            - "@net.telepay.driver.kraken"
            - "EUR"

    net.telepay.ticker.BTCxUSD:
        class: Telepay\FinancialApiBundle\Financial\Ticker\KrakenTicker
        arguments:
            - "@net.telepay.driver.kraken"
            - "USD"

    net.telepay.ticker.USDxBTC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\InversedTicker
        arguments:
            - "@net.telepay.ticker.BTCxUSD"

    net.telepay.ticker.USDxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.USDxBTC"
                - "@net.telepay.ticker.BTCxEUR"

    net.telepay.ticker.FACxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.FACxBTC"
                - "@net.telepay.ticker.BTCxEUR"


    net.telepay.ticker.FACxUSD:
        class: Telepay\FinancialApiBundle\Financial\Ticker\GetFaircoinTicker
        arguments:
            - "@net.telepay.driver.getfaircoin"
            - "USD"

    net.telepay.ticker.FACxPLN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\GetFaircoinTicker
        arguments:
            - "@net.telepay.driver.getfaircoin"
            - "PLN"


    net.telepay.ticker.FACxMXN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\GetFaircoinTicker
        arguments:
            - "@net.telepay.driver.getfaircoin"
            - "MXN"

    net.telepay.ticker.MXNxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.MXNxFAC"
                - "@net.telepay.ticker.FACxBTC"
                - "@net.telepay.ticker.BTCxEUR"

    net.telepay.ticker.PLNxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.PLNxFAC"
                - "@net.telepay.ticker.FACxBTC"
                - "@net.telepay.ticker.BTCxEUR"


    net.telepay.ticker.PLNxFAC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\InversedTicker
        arguments:
            - "@net.telepay.ticker.FACxPLN"

    net.telepay.ticker.MXNxFAC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\InversedTicker
        arguments:
            - "@net.telepay.ticker.FACxMXN"

    net.telepay.provider.btc:
        class: Telepay\FinancialApiBundle\DependencyInjection\Telepay\Providers\EasyBitcoin
        arguments:
            - "%bitcoind_user%"
            - "%bitcoind_pass%"
            - "%bitcoind_host%"
            - "%bitcoind_port%"

    net.telepay.provider.fac:
        class: Telepay\FinancialApiBundle\DependencyInjection\Telepay\Providers\EasyBitcoin
        arguments:
            - "%faircoind_user%"
            - "%faircoind_pass%"
            - "%faircoind_host%"
            - "%faircoind_port%"

    net.telepay.provider.halcash:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\Halcash
        arguments:
            - "%halcash_user%"
            - "%halcash_pass%"
            - "%halcash_alias%"

    net.telepay.provider.sabadell:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\SabadellService
        arguments:
            - "%sabadell_url_tpvv%"
            - "%sabadell_secret%"
            - "%sabadell_name%"
            - "%sabadell_code%"
            - "%sabadell_currency%"
            - "%sabadell_transaction_type%"
            - "%sabadell_terminal%"
            - "%sabadell_base_url%"
            - "%base_url%"

    net.telepay.provider.paynet_reference:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\PaynetGetBarcode
        arguments:
            - "%paynet_reference_issuer%"
            - "%paynet_reference_url%"

    net.telepay.provider.multiva:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\MultivaService
        arguments:
            - "%multiva_comcurrency%"
            - "%multiva_comaddress%"
            - "%multiva_commerchant%"
            - "%multiva_comstore%"
            - "%multiva_comterm%"
            - "%base_url%"

    net.telepay.provider.pademobile:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\PademobileRedirect
        arguments:
            - "%pademobile_client%"
            - "%pademobile_url%"
            - "%base_url%"

    net.telepay.provider.pagofacil:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\PagofacilService
        arguments:
            - "%pagofacil_id_sucursal%"
            - "%pagofacil_id_usuario%"
            - "%pagofacil_id_servicio%"
            - "%pagofacil_url_flag%"

    net.telepay.provider.safetypay:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\SafetyPayment
        arguments:
            - "%safetypay_api_key%"
            - "%safetypay_signature_key%"
            - "%safetypay_merchant_reference%"
            - "%safetypay_language%"
            - "%safetypay_tracking_code%"
            - "%safetypay_expiration_time%"
            - "%safetypay_response_format%"
            - "%safetypay_url%"

    net.telepay.provider.tc:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\ToditoCash
        arguments:
            - "%tc_contract_id%"
            - "%tc_branch_id%"
            - "%tc_url_flag%"

    net.telepay.provider.psc:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\PaysafecardPayment
        arguments:
            - "%psc_username%"
            - "%psc_password%"
            - "%base_url%"

    net.telepay.provider.spei:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\SpeiPayment
        arguments:
            - "%spei_enterprise%"
            - "%spei_account%"
            - "%spei_partner%"
            - "%spei_operant%"
            - "%spei_passphrase%"