services:

#fixed, variable

    net.telepay.config.halcash_es:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "100"
            - "2"

    net.telepay.config.halcash_pl:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "200"
            - "2"

    net.telepay.config.btc:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "0"

    net.telepay.config.fac:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "0"

