services:

    net.telepay.commons.method_manipulator:
        class: Telepay\FinancialApiBundle\DependencyInjection\Telepay\Commons\MethodManipulator

    net.telepay.commons.fee_deal:
        class: Telepay\FinancialApiBundle\DependencyInjection\Telepay\Commons\FeeDeal
        arguments:
            - "@doctrine"
            - "@doctrine_mongodb"
            - "@net.telepay.commons.balance_manipulator"
            - "@service_container"

    net.telepay.commons.balance_manipulator:
        class: Telepay\FinancialApiBundle\DependencyInjection\Telepay\Commons\BalanceManipulator
        arguments:
            - "@doctrine"

    net.telepay.commons.fee_manipulator:
        class: Telepay\FinancialApiBundle\DependencyInjection\Telepay\Commons\FeeManipulator
        arguments:
            - "@doctrine"

    net.telepay.commons.exchange_manipulator:
        class: Telepay\FinancialApiBundle\DependencyInjection\Telepay\Commons\ExchangeManipulator
        arguments:
            - "@doctrine"