services:

#fixed, variable, min_value, max_value, range, countries

    net.telepay.config.halcash_es:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "100"
            - "2"
            - "1000"
            - "60000"
            - "2000"
            - "Spain"

    net.telepay.config.halcash_pl:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "200"
            - "2"
            - "5000"
            - "300000"
            - "5000"
            - "Poland"

    net.telepay.config.btc:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "6"
            - "10000"
            - "100000000"
            - "10000000"
            - "All over the world"

    net.telepay.config.fac:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "0"
            - "100000000"
            - "1000000000000"
            - "100000000000"
            - "All over the world"

    net.telepay.config.sepa:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "100"
            - "1"
            - "5000"
            - "300000"
            - "5000"
            - "All over the world"

    net.telepay.config.cryptocapital:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "100"
            - "1"
            - "1000"
            - "25000"
            - "1000"
            - "All over the world"

    net.telepay.config.pos_pnp:
        class: Telepay\FinancialApiBundle\Financial\Methods\POSConfiguration
        arguments:
            - "pos_pnp"
            - "EUR"
            - "EUR"
            - "EUR"
            - "EUR/MXN/USD/PLN/FAC/BTC"

    net.telepay.config.pos_btc:
        class: Telepay\FinancialApiBundle\Financial\Methods\POSConfiguration
        arguments:
            - "pos_btc"
            - "BTC"
            - "BTC"
            - "EUR/MXN/USD/PLN/FAC/BTC"
            - "EUR/MXN/USD/PLN/FAC/BTC"

    net.telepay.config.pos_safetypay:
        class: Telepay\FinancialApiBundle\Financial\Methods\POSConfiguration
        arguments:
            - "pos_safetypay"
            - "MXN"
            - "MXN"
            - "MXN"
            - "EUR/MXN/USD/PLN/FAC/BTC"