services:
    
    net.telepay.ticker.FACxBTC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\BittrexTicker
        arguments:
            - "@net.telepay.driver.bittrex"
            - "fac_btc"

    net.telepay.ticker.BTCxFAC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\BittrexTicker
        arguments:
            - "@net.telepay.driver.bittrex"
            - "btc_fac"

    net.telepay.ticker.BTCxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\KrakenTicker
        arguments:
            - "@net.telepay.driver.kraken"
            - "EUR"
            - "bid"

    net.telepay.ticker.EURxBTC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\KrakenTicker
        arguments:
            - "@net.telepay.driver.kraken"
            - "EUR"
            - "ask"

    net.telepay.ticker.BTCxUSD:
        class: Telepay\FinancialApiBundle\Financial\Ticker\KrakenTicker
        arguments:
            - "@net.telepay.driver.kraken"
            - "USD"
            - "bid"

    net.telepay.ticker.USDxBTC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\KrakenTicker
        arguments:
            - "@net.telepay.driver.kraken"
            - "USD"
            - "ask"

    net.telepay.ticker.USDxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.USDxBTC"
                - "@net.telepay.ticker.BTCxEUR"

    net.telepay.ticker.EURxUSD:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.EURxBTC"
                - "@net.telepay.ticker.BTCxUSD"

    net.telepay.ticker.FACxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.FACxBTC"
                - "@net.telepay.ticker.BTCxEUR"

    net.telepay.ticker.EURxFAC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.EURxBTC"
                - "@net.telepay.ticker.BTCxFAC"

    net.telepay.ticker.FACxUSD:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.FACxBTC"
                - "@net.telepay.ticker.BTCxUSD"

    net.telepay.ticker.USDxFAC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.USDxBTC"
                - "@net.telepay.ticker.BTCxFAC"

    net.telepay.ticker.FACxPLN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.FACxBTC"
                - "@net.telepay.ticker.BTCxPLN"

    net.telepay.ticker.FACxMXN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.FACxBTC"
                - "@net.telepay.ticker.BTCxMXN"

    net.telepay.ticker.MXNxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.MXNxBTC"
                - "@net.telepay.ticker.BTCxEUR"

    net.telepay.ticker.USDxMXN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.USDxBTC"
                - "@net.telepay.ticker.BTCxMXN"

    net.telepay.ticker.MXNxUSD:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.MXNxBTC"
                - "@net.telepay.ticker.BTCxUSD"

    net.telepay.ticker.EURxMXN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.EURxBTC"
                - "@net.telepay.ticker.BTCxMXN"

    net.telepay.ticker.EURxPLN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\InversedTicker
        arguments:
            - "@net.telepay.ticker.PLNxEUR"

    net.telepay.ticker.PLNxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\HalcashTelepayTicker
        arguments:
            - "@net.telepay.driver.halcash.telepay"

    net.telepay.ticker.PLNxFAC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.PLNxEUR"
                - "@net.telepay.ticker.EURxBTC"
                - "@net.telepay.ticker.BTCxFAC"

    net.telepay.ticker.MXNxFAC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.MXNxBTC"
                - "@net.telepay.ticker.BTCxFAC"

    net.telepay.ticker.BTCxMXN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\BitsoTicker
        arguments:
            - "@net.telepay.driver.bitso"
            - "btc_mxn"

    net.telepay.ticker.MXNxBTC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\BitsoTicker
        arguments:
            - "@net.telepay.driver.bitso"
            - "mxn_btc"

    net.telepay.ticker.BTCxPLN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.BTCxEUR"
                - "@net.telepay.ticker.EURxPLN"

    net.telepay.ticker.PLNxBTC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.PLNxEUR"
                - "@net.telepay.ticker.EURxBTC"

    net.telepay.ticker.USDxPLN :
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.USDxEUR"
                - "@net.telepay.ticker.EURxPLN"

    net.telepay.ticker.PLNxUSD :
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.PLNxEUR"
                - "@net.telepay.ticker.EURxUSD"

    net.telepay.ticker.MXNxPLN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.MXNxBTC"
                - "@net.telepay.ticker.BTCxEUR"
                - "@net.telepay.ticker.EURxPLN"

    net.telepay.ticker.PLNxMXN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.PLNxEUR"
                - "@net.telepay.ticker.EURxBTC"
                - "@net.telepay.ticker.BTCxMXN"

