services:

    net.telepay.provider.btc:
        class: Telepay\FinancialApiBundle\DependencyInjection\Telepay\Providers\EasyBitcoin
        arguments:
            - "%bitcoind_user%"
            - "%bitcoind_pass%"
            - "%bitcoind_host%"
            - "%bitcoind_port%"

    net.telepay.provider.fac:
        class: Telepay\FinancialApiBundle\DependencyInjection\Telepay\Providers\EasyBitcoin
        arguments:
            - "%faircoind_user%"
            - "%faircoind_pass%"
            - "%faircoind_host%"
            - "%faircoind_port%"

    net.telepay.provider.halcash_es:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\HalcashServiceSp
        arguments:
            - "%halcash_user%"
            - "%halcash_pass%"
            - "%halcash_alias%"

    net.telepay.provider.sabadell:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\SabadellService
        arguments:
            - "%sabadell_url_tpvv%"
            - "%sabadell_secret%"
            - "%sabadell_name%"
            - "%sabadell_code%"
            - "%sabadell_currency%"
            - "%sabadell_transaction_type%"
            - "%sabadell_terminal%"
            - "%sabadell_base_url%"

    net.telepay.provider.paynet_reference:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\PaynetGetBarcode
        arguments:
            - "%paynet_reference_issuer%"

    net.telepay.provider.multiva:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\MultivaService
        arguments:
            - "%multiva_comcurrency%"
            - "%multiva_comaddress%"
            - "%multiva_commerchant%"
            - "%multiva_comstore%"
            - "%multiva_comterm%"
            - "%multiva_base_url%"

    net.telepay.provider.pademobile:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\PademobileRedirect
        arguments:
            - "%pademobile_client%"
            - "%pademobile_url%"
            - "%pademobile_env_url%"

    net.telepay.provider.pagofacil:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\PagofacilService
        arguments:
            - "%pagofacil_id_sucursal%"
            - "%pagofacil_id_usuario%"
            - "%pagofacil_id_servicio%"
            - "%pagofacil_url_flag%"

    net.telepay.provider.safetypay:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\SafetyPayment
        arguments:
            - "%safetypay_api_key%"
            - "%safetypay_signature_key%"
            - "%safetypay_merchant_reference%"
            - "%safetypay_language%"
            - "%safetypay_tracking_code%"
            - "%safetypay_expiration_time%"
            - "%safetypay_response_format%"
            - "%safetypay_url%"

    net.telepay.provider.tc:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\ToditoCash
        arguments:
            - "%tc_contract_id%"
            - "%tc_branch_id%"
            - "%tc_url_flag%"

    net.telepay.provider.psc:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\PaysafecardPayment
        arguments:
            - "%psc_username%"
            - "%psc_password%"
            - "%psc_env_url%"

    net.telepay.provider.ukash_generate:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\UkashBarcode
        arguments:
            - "%ukash_generate_username%"
            - "%ukash_generate_password%"
            - "%ukash_generate_brand_id%"
            - "%ukash_generate_production_flag%"

    net.telepay.provider.ukash_redemption:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\UkashBarcode
        arguments:
            - "%ukash_redemption_username%"
            - "%ukash_redemption_password%"
            - "%ukash_redemption_brand_id%"
            - "%ukash_redemption_production_flag%"
