services:


    net.telepay.provider.rec:
        class: Telepay\FinancialApiBundle\DependencyInjection\Telepay\Providers\EasyBitcoin
        arguments:
            - "%rec_user%"
            - "%rec_pass%"
            - "%rec_host%"
            - "%rec_port%"

    net.telepay.provider.sepa_in:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\SepaIn
        arguments:

    net.telepay.provider.sepa_out:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Libs\SepaOut
        arguments:
