services:

    net.telepay.driver.provider:
        class: Telepay\FinancialApiBundle\Financial\ObjectRegister
        arguments:
            drivers:
                - "@net.telepay.driver.easybitcoin.rec"

    net.telepay.driver.easybitcoin.rec:
        class: Telepay\FinancialApiBundle\Financial\Driver\EasyBitcoinDriver
        arguments:
            - "%rec_user%"
            - "%rec_pass%"
            - "%rec_host%"
            - "%rec_port%"
