services:
    
    net.telepay.ticker.FACxBTC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\BittrexTicker
        arguments:
            - "@net.telepay.driver.bittrex"
            - "fac_btc"
            - "FAIR"

    net.telepay.ticker.BTCxFAC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\BittrexTicker
        arguments:
            - "@net.telepay.driver.bittrex"
            - "btc_fac"
            - "FAIR"

    net.telepay.ticker.BTCxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\KrakenTicker
        arguments:
            - "@net.telepay.driver.kraken"
            - "EUR"
            - "bid"

    net.telepay.ticker.EURxBTC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\KrakenTicker
        arguments:
            - "@net.telepay.driver.kraken"
            - "EUR"
            - "ask"

    net.telepay.ticker.BTCxUSD:
        class: Telepay\FinancialApiBundle\Financial\Ticker\KrakenTicker
        arguments:
            - "@net.telepay.driver.kraken"
            - "USD"
            - "bid"

    net.telepay.ticker.USDxBTC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\KrakenTicker
        arguments:
            - "@net.telepay.driver.kraken"
            - "USD"
            - "ask"

    net.telepay.ticker.USDxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.USDxBTC"
                - "@net.telepay.ticker.BTCxEUR"

    net.telepay.ticker.EURxUSD:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.EURxBTC"
                - "@net.telepay.ticker.BTCxUSD"

    net.telepay.ticker.FACxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.FACxBTC"
                - "@net.telepay.ticker.BTCxEUR"

    net.telepay.ticker.EURxFAC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.EURxBTC"
                - "@net.telepay.ticker.BTCxFAC"

    net.telepay.ticker.FACxUSD:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.FACxBTC"
                - "@net.telepay.ticker.BTCxUSD"

    net.telepay.ticker.USDxFAC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.USDxBTC"
                - "@net.telepay.ticker.BTCxFAC"

    net.telepay.ticker.FACxPLN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.FACxBTC"
                - "@net.telepay.ticker.BTCxPLN"

    net.telepay.ticker.FACxMXN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.FACxBTC"
                - "@net.telepay.ticker.BTCxMXN"

    net.telepay.ticker.MXNxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.MXNxBTC"
                - "@net.telepay.ticker.BTCxEUR"

    net.telepay.ticker.USDxMXN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.USDxBTC"
                - "@net.telepay.ticker.BTCxMXN"

    net.telepay.ticker.MXNxUSD:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.MXNxBTC"
                - "@net.telepay.ticker.BTCxUSD"

    net.telepay.ticker.EURxMXN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.EURxBTC"
                - "@net.telepay.ticker.BTCxMXN"

    net.telepay.ticker.EURxPLN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\InversedTicker
        arguments:
            - "@net.telepay.ticker.PLNxEUR"

    net.telepay.ticker.PLNxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\HalcashTelepayTicker
        arguments:
            - "@net.telepay.driver.halcash.telepay"

    net.telepay.ticker.PLNxFAC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.PLNxEUR"
                - "@net.telepay.ticker.EURxBTC"
                - "@net.telepay.ticker.BTCxFAC"

    net.telepay.ticker.MXNxFAC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.MXNxBTC"
                - "@net.telepay.ticker.BTCxFAC"

    net.telepay.ticker.BTCxMXN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\BitsoTicker
        arguments:
            - "@net.telepay.driver.bitso"
            - "btc_mxn"

    net.telepay.ticker.MXNxBTC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\BitsoTicker
        arguments:
            - "@net.telepay.driver.bitso"
            - "mxn_btc"

    net.telepay.ticker.BTCxPLN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.BTCxEUR"
                - "@net.telepay.ticker.EURxPLN"

    net.telepay.ticker.PLNxBTC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.PLNxEUR"
                - "@net.telepay.ticker.EURxBTC"

    net.telepay.ticker.USDxPLN :
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.USDxEUR"
                - "@net.telepay.ticker.EURxPLN"

    net.telepay.ticker.PLNxUSD :
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.PLNxEUR"
                - "@net.telepay.ticker.EURxUSD"

    net.telepay.ticker.MXNxPLN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.MXNxBTC"
                - "@net.telepay.ticker.BTCxEUR"
                - "@net.telepay.ticker.EURxPLN"

    net.telepay.ticker.PLNxMXN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.PLNxEUR"
                - "@net.telepay.ticker.EURxBTC"
                - "@net.telepay.ticker.BTCxMXN"

    net.telepay.ticker.FAIRPxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\GetFaircoinTicker
        arguments:
            - "@net.telepay.driver.getfaircoin"
            - "EUR"

    net.telepay.ticker.EURxFAIRP:
        class: Telepay\FinancialApiBundle\Financial\Ticker\InversedTicker
        arguments:
            - "@net.telepay.ticker.FAIRPxEUR"


    net.telepay.ticker.FAIRPxUSD:
        class: Telepay\FinancialApiBundle\Financial\Ticker\GetFaircoinTicker
        arguments:
            - "@net.telepay.driver.getfaircoin"
            - "USD"

    net.telepay.ticker.USDxFAIRP:
        class: Telepay\FinancialApiBundle\Financial\Ticker\InversedTicker
        arguments:
            - "@net.telepay.ticker.FAIRPxUSD"


    net.telepay.ticker.FAIRPxPLN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\GetFaircoinTicker
        arguments:
            - "@net.telepay.driver.getfaircoin"
            - "PLN"

    net.telepay.ticker.PLNxFAIRP:
        class: Telepay\FinancialApiBundle\Financial\Ticker\InversedTicker
        arguments:
            - "@net.telepay.ticker.FAIRPxPLN"


    net.telepay.ticker.FAIRPxMXN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\GetFaircoinTicker
        arguments:
            - "@net.telepay.driver.getfaircoin"
            - "MXN"

    net.telepay.ticker.MXNxFAIRP:
        class: Telepay\FinancialApiBundle\Financial\Ticker\InversedTicker
        arguments:
            - "@net.telepay.ticker.FAIRPxMXN"

    net.telepay.ticker.FAIRPxBTC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.FAIRPxEUR"
                - "@net.telepay.ticker.EURxBTC"

    net.telepay.ticker.BTCxFAIRP:
        class: Telepay\FinancialApiBundle\Financial\Ticker\InversedTicker
        arguments:
            - "@net.telepay.ticker.FAIRPxBTC"

    net.telepay.ticker.FAIRPxFAC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.FAIRPxEUR"
                - "@net.telepay.ticker.EURxFAC"

    net.telepay.ticker.FACxFAIRP:
        class: Telepay\FinancialApiBundle\Financial\Ticker\InversedTicker
        arguments:
            - "@net.telepay.ticker.FAIRPxFAC"

    net.telepay.ticker.ETHxBTC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\BittrexTicker
        arguments:
            - "@net.telepay.driver.bittrex"
            - "eth_btc"
            - "ETH"

    net.telepay.ticker.BTCxETH:
        class: Telepay\FinancialApiBundle\Financial\Ticker\BittrexTicker
        arguments:
            - "@net.telepay.driver.bittrex"
            - "btc_eth"
            - "ETH"

    net.telepay.ticker.ETHxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.ETHxBTC"
                - "@net.telepay.ticker.BTCxEUR"

    net.telepay.ticker.EURxETH:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.EURxBTC"
                - "@net.telepay.ticker.BTCxETH"

    net.telepay.ticker.ETHxFAC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.ETHxBTC"
                - "@net.telepay.ticker.BTCxFAC"

    net.telepay.ticker.FACxETH:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.FACxBTC"
                - "@net.telepay.ticker.BTCxETH"

    net.telepay.ticker.ETHxUSD:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.ETHxBTC"
                - "@net.telepay.ticker.BTCxUSD"

    net.telepay.ticker.USDxETH:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.USDxBTC"
                - "@net.telepay.ticker.BTCxETH"

    net.telepay.ticker.ETHxMXN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.ETHxBTC"
                - "@net.telepay.ticker.BTCxMXN"

    net.telepay.ticker.MXNxETH:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.MXNxBTC"
                - "@net.telepay.ticker.BTCxETH"

    net.telepay.ticker.ETHxPLN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.ETHxBTC"
                - "@net.telepay.ticker.BTCxPLN"

    net.telepay.ticker.PLNxETH:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.PLNxEUR"
                - "@net.telepay.ticker.EURxBTC"
                - "@net.telepay.ticker.BTCxETH"

    net.telepay.ticker.FAIRPxETH:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.FAIRPxEUR"
                - "@net.telepay.ticker.EURxETH"

    net.telepay.ticker.ETHxFAIRP:
        class: Telepay\FinancialApiBundle\Financial\Ticker\InversedTicker
        arguments:
            - "@net.telepay.ticker.FAIRPxETH"

    net.telepay.ticker.CREAxBTC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\BittrexTicker
        arguments:
            - "@net.telepay.driver.bittrex"
            - "crea_btc"
            - "FAIR"

    net.telepay.ticker.BTCxCREA:
        class: Telepay\FinancialApiBundle\Financial\Ticker\BittrexTicker
        arguments:
            - "@net.telepay.driver.bittrex"
            - "btc_crea"
            - "FAIR"

    net.telepay.ticker.CREAxEUR:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.CREAxBTC"
                - "@net.telepay.ticker.BTCxEUR"

    net.telepay.ticker.EURxCREA:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.EURxBTC"
                - "@net.telepay.ticker.BTCxCREA"

    net.telepay.ticker.CREAxUSD:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.CREAxBTC"
                - "@net.telepay.ticker.BTCxUSD"

    net.telepay.ticker.USDxCREA:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.USDxBTC"
                - "@net.telepay.ticker.BTCxCREA"

    net.telepay.ticker.CREAxMXN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.CREAxBTC"
                - "@net.telepay.ticker.BTCxMXN"

    net.telepay.ticker.MXNxCREA:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.MXNxBTC"
                - "@net.telepay.ticker.BTCxCREA"

    net.telepay.ticker.CREAxPLN:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.CREAxBTC"
                - "@net.telepay.ticker.BTCxPLN"

    net.telepay.ticker.PLNxCREA:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.PLNxEUR"
                - "@net.telepay.ticker.EURxBTC"
                - "@net.telepay.ticker.BTCxCREA"

    net.telepay.ticker.CREAxFAC:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.CREAxBTC"
                - "@net.telepay.ticker.BTCxFAC"

    net.telepay.ticker.FACxCREA:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.FACxBTC"
                - "@net.telepay.ticker.BTCxCREA"

    net.telepay.ticker.ETHxCREA:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.ETHxBTC"
                - "@net.telepay.ticker.BTCxCREA"

    net.telepay.ticker.CREAxETH:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.CREAxBTC"
                - "@net.telepay.ticker.BTCxETH"

    net.telepay.ticker.FAIRPxCREA:
        class: Telepay\FinancialApiBundle\Financial\Ticker\ChainedTicker
        arguments:
            exchange_chain:
                - "@net.telepay.ticker.FAIRPxEUR"
                - "@net.telepay.ticker.EURxCREA"

    net.telepay.ticker.CREAxFAIRP:
        class: Telepay\FinancialApiBundle\Financial\Ticker\InversedTicker
        arguments:
            - "@net.telepay.ticker.FAIRPxCREA"