services:

#SWIFT CONFIGURATION ONLY WITH THE OUT METHOD
#fixed, variable, min_value, max_value, range, countries

    net.telepay.config.halcash_es:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "150"
            - "2"
            - "2000"
            - "60000"
            - "1000"
            - "Spain"

    net.telepay.config.halcash_pl:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "2000"
            - "2"
            - "5000"
            - "300000"
            - "5000"
            - "Poland"

    net.telepay.config.btc:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "6"
            - "10000"
            - "100000000"
            - "10000000"
            - "All over the world"

    net.telepay.config.fac:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "0"
            - "100000000"
            - "1000000000000"
            - "100000000000"
            - "All over the world"

    net.telepay.config.sepa:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "1"
            - "5000"
            - "300000"
            - "5000"
            - "All over the world"

    net.telepay.config.cryptocapital:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "1"
            - "1000"
            - "25000"
            - "1000"
            - "All over the world"

    net.telepay.config.pos_pnp:
        class: Telepay\FinancialApiBundle\Financial\Methods\POSConfiguration
        arguments:
            - "pos_pnp"
            - "EUR"
            - "EUR"
            - "EUR"
            - "EUR/MXN/USD/PLN/FAC/BTC"

    net.telepay.config.pos_btc:
        class: Telepay\FinancialApiBundle\Financial\Methods\POSConfiguration
        arguments:
            - "pos_btc"
            - "BTC"
            - "BTC"
            - "EUR/MXN/USD/PLN/FAC/BTC"
            - "EUR/MXN/USD/PLN/FAC/BTC"

    net.telepay.config.pos_fac:
        class: Telepay\FinancialApiBundle\Financial\Methods\POSConfiguration
        arguments:
            - "pos_fac"
            - "FAC"
            - "FAC"
            - "EUR/MXN/USD/PLN/FAC/BTC"
            - "EUR/MXN/USD/PLN/FAC/BTC"

    net.telepay.config.pos_safetypay:
        class: Telepay\FinancialApiBundle\Financial\Methods\POSConfiguration
        arguments:
            - "pos_safetypay"
            - "MXN"
            - "MXN"
            - "MXN"
            - "EUR/MXN/USD/PLN/FAC/BTC"

    net.telepay.config.pos_sabadell:
        class: Telepay\FinancialApiBundle\Financial\Methods\POSConfiguration
        arguments:
            - "pos_sabadell"
            - "EUR"
            - "EUR"
            - "EUR/MXN/USD/PLN/FAC/BTC"
            - "EUR/MXN/USD/PLN/FAC/BTC"


#NEW SWIFT CONFIGURATION
#fixed, variable, min_value, max_value, range, countries, currency, expires_in

    net.telepay.config.btc.halcash_es:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "150"
            - "1"
            - "2000"
            - "60000"
            - "1000"
            - "Spain"
            - "EUR"
            - "1200"
            - "0"

    net.telepay.config.btc.halcash_pl:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "2000"
            - "1"
            - "5000"
            - "300000"
            - "5000"
            - "Poland"
            - "PLN"
            - "1200"
            - "0"

    net.telepay.config.btc.cryptocapital:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "1"
            - "1000"
            - "25000"
            - "500"
            - "All over the world"
            - "EUR"
            - "1200"
            - "0"

    net.telepay.config.btc.sepa:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "1"
            - "5000"
            - "300000"
            - "5000"
            - "All over the world"
            - "EUR"
            - "86400"
            - "24"

    net.telepay.config.btc.easypay:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "100"
            - "2"
            - "5000"
            - "300000"
            - "5000"
            - "All over the world"
            - "EUR"
            - "86400"
            - "0"

    net.telepay.config.sepa.btc:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "1"
            - "5000"
            - "50000"
            - "1000"
            - "Europe"
            - "EUR"
            - "172800"
            - "24"

    net.telepay.config.sepa.fac:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "1"
            - "5000"
            - "50000"
            - "1000"
            - "Europe"
            - "EUR"
            - "172800"
            - "24"

    net.telepay.config.easypay.btc:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "0"
            - "1000"
            - "50000"
            - "1000"
            - "Greece"
            - "EUR"
            - "86400"
            - "24"

    net.telepay.config.safetypay.btc:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "6"
            - "50000"
            - "1000000"
            - "50000"
            - "All over the world"
            - "MXN"
            - "15"
            - "0"

    net.telepay.config.safetypay.fac:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "6"
            - "50000"
            - "1000000"
            - "50000"
            - "All over the world"
            - "MXN"
            - "15"
            - "0"

    net.telepay.config.paynet_reference.btc:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "6"
            - "5000"
            - "100000"
            - "5000"
            - "Mexico"
            - "MXN"
            - "1209600"
            - "0"

    net.telepay.config.paynet_reference.fac:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "6"
            - "5000"
            - "100000"
            - "5000"
            - "Mexico"
            - "MXN"
            - "1209600"
            - "0"

    net.telepay.config.fac.halcash_es:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "150"
            - "1"
            - "2000"
            - "60000"
            - "1000"
            - "Spain"
            - "EUR"
            - "1200"
            - "0"

    net.telepay.config.fac.halcash_pl:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "2000"
            - "1"
            - "5000"
            - "300000"
            - "5000"
            - "Poland"
            - "PLN"
            - "1200"
            - "0"

    net.telepay.config.easypay.fac:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "4"
            - "1000"
            - "50000"
            - "1000"
            - "Greece"
            - "EUR"
            - "86400"
            - "24"

    net.telepay.config.fac.sepa:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "1"
            - "5000"
            - "300000"
            - "5000"
            - "All over the world"
            - "EUR"
            - "86400"
            - "0"

    net.telepay.config.fac.cryptocapital:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "1"
            - "1000"
            - "25000"
            - "500"
            - "All over the world"
            - "EUR"
            - "1200"
            - "0"

    net.telepay.config.teleingreso.fac:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "6"
            - "1000"
            - "60000"
            - "1000"
            - "Spain"
            - "EUR"
            - "1296000"
            - "0"

    net.telepay.config.teleingreso.btc:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "6"
            - "1000"
            - "60000"
            - "1000"
            - "Spain"
            - "EUR"
            - "1296000"
            - "0"

    net.telepay.config.sepa.eth:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "2"
            - "5000"
            - "50000"
            - "1000"
            - "Europe"
            - "EUR"
            - "172800"
            - "24"

    net.telepay.config.btc.eth:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "2"
            - "600000"
            - "30000000"
            - "600000"
            - "All over the world"
            - "BTC"
            - "1200"
            - "0"

    net.telepay.config.fac.eth:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "2"
            - "2000000000"
            - "160000000000"
            - "2000000000"
            - "All over the world"
            - "FAC"
            - "1200"
            - "0"

    net.telepay.config.teleingreso_usa.btc:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "3"
            - "10000"
            - "60000"
            - "1000"
            - "USA"
            - "USD"
            - "172800"
            - "0"

    net.telepay.config.teleingreso_pt.btc:
        class: Telepay\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "4"
            - "10000"
            - "60000"
            - "1000"
            - "Portugal"
            - "EUR"
            - "172800"
            - "0"


#POS CONFIGURATIONS
#$type, $currency, $default_currency, $allowed_currencies_in, $allowed_currencies_out

    net.telepay.config.pos_pnp:
        class: Telepay\FinancialApiBundle\Financial\Methods\POSConfiguration
        arguments:
            - "pos_pnp"
            - "EUR"
            - "EUR"
            - "EUR"
            - "EUR/MXN/USD/PLN/FAC/BTC"

    net.telepay.config.pos_btc:
        class: Telepay\FinancialApiBundle\Financial\Methods\POSConfiguration
        arguments:
            - "pos_btc"
            - "BTC"
            - "BTC"
            - "EUR/MXN/USD/PLN/FAC/BTC"
            - "EUR/MXN/USD/PLN/FAC/BTC"

    net.telepay.config.pos_fac:
        class: Telepay\FinancialApiBundle\Financial\Methods\POSConfiguration
        arguments:
            - "pos_fac"
            - "FAC"
            - "FAC"
            - "EUR/MXN/USD/PLN/FAC/BTC"
            - "EUR/MXN/USD/PLN/FAC/BTC"

    net.telepay.config.pos_safetypay:
        class: Telepay\FinancialApiBundle\Financial\Methods\POSConfiguration
        arguments:
            - "pos_safetypay"
            - "MXN"
            - "MXN"
            - "MXN/EUR"
            - "EUR/MXN/USD/PLN/FAC/BTC"

    net.telepay.config.pos_sabadell:
        class: Telepay\FinancialApiBundle\Financial\Methods\POSConfiguration
        arguments:
            - "pos_sabadell"
            - "EUR"
            - "EUR"
            - "EUR/MXN/USD/PLN/FAC/BTC"
            - "EUR/MXN/USD/PLN/FAC/BTC"