services:
    
    net.telepay.trader.FACxBTC:
        class: Telepay\FinancialApiBundle\Financial\Wallet\BittrexWallet
        arguments:
            - "@net.telepay.driver.bittrex"

    net.telepay.trader.BTCxEUR:
        class: Telepay\FinancialApiBundle\Financial\Wallet\KrakenWallet
        arguments:
            - "@net.telepay.driver.kraken"