services:

    net.telepay.driver.bitso:
        class: Telepay\FinancialApiBundle\Financial\Driver\BitsoDriver

    net.telepay.driver.kraken:
        class: Payward\KrakenAPI
        arguments:
            - "%kraken_api_key%"
            - "%kraken_private_key%"

    net.telepay.driver.bittrex:
        class: Telepay\FinancialApiBundle\Financial\Driver\BittrexDriver
        arguments:
            - "%bittrex_api_url%"
            - "%bittrex_api_key%"
            - "%bittrex_api_secret%"

    net.telepay.driver.getfaircoin:
        class: GetFaircoin\Ticker

    net.telepay.driver.halcash.telepay:
        class: Telepay\FinancialApiBundle\Financial\Driver\HalcashTelepayDriver
        arguments:
            - "%halcash_user%"
            - "%halcash_pass%"
            - "%halcash_alias%"
            - "%halcash_url%"

    net.telepay.driver.easybitcoin.btc:
        class: Telepay\FinancialApiBundle\Financial\Driver\EasyBitcoinDriver
        arguments:
            - "%bitcoind_user%"
            - "%bitcoind_pass%"
            - "%bitcoind_host%"
            - "%bitcoind_port%"

    net.telepay.driver.easybitcoin.fac:
        class: Telepay\FinancialApiBundle\Financial\Driver\EasyBitcoinDriver
        arguments:
            - "%faircoind_user%"
            - "%faircoind_pass%"
            - "%faircoind_host%"
            - "%faircoind_port%"

    net.telepay.driver.abanca_issue_hal:
        class: Telepay\FinancialApiBundle\Financial\Driver\RobotUnionDriver
        arguments:
            - "abanca_issue_hal"


