
######################### TEST ############################

arbaf_services_test:
    pattern:  /v1/services/test
    defaults: { _controller: Arbaf\FinancialApiBundle\Controller\Services\TestService::index, _format: ~ }
    requirements:
        _method: GET

#arbaf_financial_api_test_auth:
#    pattern:  /services/test
#    defaults: { _controller: ArbafFinancialApiBundle:Test:auth, _format: ~ }
#    requirements:
#        _method: GET
#        access-key: "[a-zA-Z0-9]+"
#        nonce: "[a-zA-Z0-9]+"
#        timestamp: "[0-9]+"
#        algorithm: "SHA256"
#        signature: "[a-zA-Z0-9]+"

######################## END TEST ############################

##################### CLIENTS ############################

arbaf_financial_api_clients_index:
    pattern:  /admin/clients
    defaults: { _controller: Arbaf\FinancialApiBundle\Controller\Admin\ClientsController::indexAction, _format: ~ }
    requirements:
        _method: GET

#arbaf_financial_api_clients_get:
#    pattern:  /admin/clients/{id}
#    defaults: { _controller: ArbafFinancialApiBundle:Clients:get, _format: ~ }
#    requirements:
#        _method: GET
#        id: "[0-9]+"
#
#arbaf_financial_api_clients_add:
#    pattern:  /admin/clients
#    defaults: { _controller: ArbafFinancialApiBundle:Clients:add, _format: ~ }
#    requirements:
#        _method: POST
#        name: "string"
#        email: "email"
#        password: "string"
#
#arbaf_financial_api_clients_edit:
#    pattern:  /admin/clients/{id}
#    defaults: { _controller: ArbafFinancialApiBundle:Clients:edit, _format: ~ }
#    requirements:
#        _method: PUT
#        id: "[0-9]+"
#        name: "string"
#        email: "email"
#        password: "string"
#
#arbaf_financial_api_clients_delete:
#    pattern:  /admin/clients/{id}
#    defaults: { _controller: ArbafFinancialApiBundle:Clients:delete, _format: ~ }
#    requirements:
#        _method: DELETE
#        id: "[0-9]+"

######################## END CLIENTS ########################
##################### USERS ############################

arbaf_financial_api_users_index:
    pattern:  /manager/users
    defaults: { _controller: Arbaf\FinancialApiBundle\Controller\Manager\UsersController::indexAction, _format: ~ }
    requirements:
        _method: GET


arbaf_financial_api_users_get:
    pattern:  /manager/users/{id}
    defaults: { _controller: Arbaf\FinancialApiBundle\Controller\Manager\UsersController::showAction, _format: ~ }
    requirements:
        _method: GET
        id: "[0-9]+"

arbaf_financial_api_users_add:
    pattern:  /manager/users
    defaults: { _controller: Arbaf\FinancialApiBundle\Controller\Manager\UsersController::createAction, _format: ~ }
    requirements:
        _method: POST
        name: "string"
        email: "email"
        password: "string"


arbaf_financial_api_users_update:
    pattern:  /manager/users/{id}
    defaults: { _controller: Arbaf\FinancialApiBundle\Controller\Manager\UsersController::updateAction, _format: ~ }
    requirements:
        _method: PUT
        id: "[0-9]+"
        name: "string"
        email: "email"
        password: "string"

arbaf_financial_api_users_delete:
    pattern:  /manager/users/{id}
    defaults: { _controller: Arbaf\FinancialApiBundle\Controller\Manager\UsersController::deleteAction, _format: ~ }
    requirements:
        _method: DELETE
        id: "[0-9]+"

######################## END USERS ########################
##################### GROUPS ############################

arbaf_financial_api_groups_index:
    pattern:  /admin/groups
    defaults: { _controller: ArbafFinancialApiBundle:Groups:index, _format: ~ }
    requirements:
        _method: GET

arbaf_financial_api_groups_get:
    pattern:  /admin/groups/{id}
    defaults: { _controller: ArbafFinancialApiBundle:Groups:get, _format: ~ }
    requirements:
        _method: GET
        id: "[0-9]+"

arbaf_financial_api_groups_add:
    pattern:  /admin/groups
    defaults: { _controller: ArbafFinancialApiBundle:Groups:add, _format: ~ }
    requirements:
        _method: POST
        name: "[a-zA-Z0-9_]+"

arbaf_financial_api_groups_delete:
    pattern:  /admin/groups/{id}
    defaults: { _controller: ArbafFinancialApiBundle:Groups:delete, _format: ~ }
    requirements:
        _method: DELETE
        id: "[0-9]+"

######################## END GROUPS ########################


arbaf_financial_api_groups_add_roles:
    pattern:  /admin/groups/{id}/roles
    defaults: { _controller: ArbafFinancialApiBundle:GroupsRoles:addRoles, _format: ~ }
    requirements:
        _method: POST
        rol_name: "ROLE_[A-Z_]+"

arbaf_financial_api_groups_delete_roles:
    pattern:  /admin/groups/{id}/roles/{rol_name}
    defaults: { _controller: ArbafFinancialApiBundle:GroupsRoles:deleteRoles, _format: ~ }
    requirements:
        _method: DELETE
        id: "[0-9]+"
        rol_name: "ROLE_[A-Z_]+"



arbaf_financial_api_users_add_groups:
    pattern:  /admin/users/{id}/groups
    defaults: { _controller: ArbafFinancialApiBundle:UsersGroups:addGroups, _format: ~ }
    requirements:
        _method: POST
        group_id: "[0-9]+"

arbaf_financial_api_users_delete_groups:
    pattern:  /admin/users/{id}/groups/{group_id}
    defaults: { _controller: ArbafFinancialApiBundle:UsersGroups:deleteGroups, _format: ~ }
    requirements:
        _method: DELETE
        id: "[0-9]+"
        group_id: "[0-9]+"


arbaf_financial_api_services_index:
    pattern:  /services
    defaults: { _controller: ArbafFinancialApiBundle:Services:index, _format: ~ }
    requirements:
        _method: GET

arbaf_financial_api_services_test_do:
    pattern:  /services/test
    defaults: { _controller: ArbafFinancialApiBundle:ServicesTest:do, _format: ~ }
    requirements:
        _method: POST


arbaf_financial_api_services_netpay_pos_register:
    pattern:  /services/netpay/pos/register
    defaults: { _controller: Arbaf\FinancialApiBundle\Controller\Services\ServicesNetpayPosController::registerAction, _format: ~ }
    requirements:
        _method: POST


arbaf_financial_api_services_netpay_pos_transaction:
    pattern:  /services/netpay/pos/transaction
    defaults: { _controller: ArbafFinancialApiBundle:ServicesNetpayPos:transaction, _format: ~ }
    requirements:
        _method: POST

arbaf_financial_api_services_paynet_reference_generate:
    pattern:  /services/paynet/reference/generate
    defaults: { _controller: ArbafFinancialApiBundle:ServicesPaynetReference:generate, _format: ~ }
    requirements:
        _method: POST

arbaf_financial_api_services_paynet_reference_status:
    pattern:  /services/paynet/reference/status
    defaults: { _controller: ArbafFinancialApiBundle:ServicesPaynetReference:status, _format: ~ }
    requirements:
        _method: POST

arbaf_financial_api_services_toditocash_payservices_request:
    pattern:  /services/toditocash/payservices/request
    defaults: { _controller: ArbafFinancialApiBundle:ServicesToditocashPayservices:request, _format: ~ }
    requirements:
        _method: POST

arbaf_financial_api_services_toditocash_payservices_reverso:
    pattern:  /services/toditocash/payservices/reverso
    defaults: { _controller: ArbafFinancialApiBundle:ServicesToditocashPayservices:reverso, _format: ~ }
    requirements:
        _method: POST

arbaf_financial_api_services_paynet_payment_info:
    pattern:  /services/paynet/payment/info
    defaults: { _controller: ArbafFinancialApiBundle:ServicesPaynetPayment:info, _format: ~ }
    requirements:
        _method: POST

arbaf_financial_api_services_paynet_payment_ejecuta:
    pattern:  /services/paynet/payment/ejecuta
    defaults: { _controller: ArbafFinancialApiBundle:ServicesPaynetPayment:ejecuta, _format: ~ }
    requirements:
        _method: POST

arbaf_financial_api_services_paynet_payment_reversa:
    pattern:  /services/paynet/payment/reversa
    defaults: { _controller: ArbafFinancialApiBundle:ServicesPaynetPayment:reversa, _format: ~ }
    requirements:
        _method: POST
