
arbaf_financial_api_test_plain:
    pattern:  /test/plain
    defaults: { _controller: ArbafFinancialApiBundle:Test:plain, _format: ~ }
    requirements:
        _method: GET

arbaf_financial_api_test_auth:
    pattern:  /test/auth
    defaults: { _controller: ArbafFinancialApiBundle:Test:auth, _format: ~ }
    requirements:
        _method: GET

arbaf_financial_api_users_index:
    pattern:  /users
    defaults: { _controller: ArbafFinancialApiBundle:User:index, _format: ~ }
    requirements:
        _method: GET

arbaf_financial_api_users_get:
    pattern:  /users/{id}
    defaults: { _controller: ArbafFinancialApiBundle:User:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"