services:
    signature.security.authentication.provider:
        class: Arbaf\FinancialApiBundle\Security\Authentication\Provider\SignatureAuthenticationProvider
        arguments: ["", "%kernel.cache_dir%/security/nonces"]

    signature.security.authentication.listener:
        class: Arbaf\FinancialApiBundle\Security\Firewall\SignatureListener
        arguments: ["@security.context", "@security.authentication.manager"]

    access_key.security.user_provider:
        class: Arbaf\FinancialApiBundle\Security\AccessKeyUserProvider
        arguments: ["@fos_user.user_manager"]
