services:
    api.security.authentication.provider:
        class: Arbaf\FinancialApiBundle\Security\Authentication\Provider\ApiAuthenticationProvider
        arguments: ["", "%kernel.cache_dir%/security/nonces"]

    api.security.authentication.listener:
        class: Arbaf\FinancialApiBundle\Security\Firewall\ApiListener
        arguments: ["@security.context", "@security.authentication.manager"]

    api.security.user_provider:
        class: Arbaf\FinancialApiBundle\Security\ApiUserProvider
        arguments: ["@fos_user.user_manager"]

