name: REC
title: Rec Api Docs
subtitle: Rec barcelona
url: https://api.rec.barcelona
favicon_path: https://rec.barcelona/wp-content/uploads/2018/04/favicon_16_rec_simbol.png
logo_header_path: https://rec.barcelona/wp-content/uploads/2018/04/Group-3116@2x.png

