
service_analytics:
    pattern:  /analytics/v1/{service_cname}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\AnalyticsController::process, _format: ~ }
    requirements:
        _method: GET
        service_cname: "[a-z0-9_]+"
        id: "[a-z0-9]+"

service_analytics_id:
    pattern:  /analytics/v1/{service_cname}/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\AnalyticsController::process, _format: ~ }
    requirements:
        _method: GET
        service_cname: "[a-z0-9_]+"
        id: "[a-z0-9]+"

service_analytics_test:
    pattern:  /test/analytics/v1/{service_cname}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\AnalyticsController::processTest, _format: ~ }
    requirements:
        _method: GET
        service_cname: "[a-z0-9_]+"
        id: "[a-z0-9]+"

service_analytics_test_id:
    pattern:  /test/analytics/v1/{service_cname}/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\AnalyticsController::processTest, _format: ~ }
    requirements:
        _method: GET
        service_cname: "[a-z0-9_]+"
        id: "[a-z0-9]+"

