
accounts_v3_search:
    path:  /{role}/v3/accounts/search
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\CRUD\AccountsController::searchAction }
    methods: [GET]
    requirements:
        role: "[a-z]+"

##################### CRUD / V3 ############################

crud_v3_search:
    path:  /{role}/v3/{object}/search
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\CRUD\CRUDController::searchAction }
    methods: [GET]
    requirements:
        role: "[a-z]+"
        object: "[a-z_]+"

crud_v3_export:
    path:  /{role}/v3/{object}/export
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\CRUD\CRUDController::exportAction }
    methods: [GET]
    requirements:
        role: "[a-z]+"
        object: "[a-z_]+"

crud_v3_index:
    path:  /{role}/v3/{object}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\CRUD\CRUDController::indexAction }
    methods: [GET]
    requirements:
        role: "[a-z]+"
        object: "[a-z_]+"

crud_v3_show:
    path:  /{role}/v3/{object}/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\CRUD\CRUDController::showAction }
    methods: [GET]
    requirements:
        role: "[a-z]+"
        object: "[a-z_]+"
        id: "[0-9]+"

crud_v3_update:
    path:  /{role}/v3/{object}/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\CRUD\CRUDController::updateAction }
    methods: [PUT]
    requirements:
        role: "[a-z]+"
        object: "[a-z_]+"
        id: "[0-9]+"

crud_v3_delete:
    path:  /{role}/v3/{object}/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\CRUD\CRUDController::deleteAction }
    methods: [DELETE]
    requirements:
        role: "[a-z]+"
        object: "[a-z_]+"
        id: "[0-9]+"
