

##################### CRUD / V3 / ACCOUNTS ############################

accounts_v3_search:
    path:  /{role}/v3/accounts/search
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\CRUD\AccountsController::searchAction }
    methods: [GET]

accounts_v3_index:
    path:  /{role}/v3/accounts
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\CRUD\AccountsController::indexAction }
    methods: [GET]

accounts_v3_show:
    path:  /{role}/v3/accounts/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\CRUD\AccountsController::showAction }
    methods: [GET]

accounts_v3_update:
    path:  /{role}/v3/accounts/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\CRUD\AccountsController::updateAction }
    methods: [PUT]

accounts_v3_delete:
    path:  /{role}/v3/accounts/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\CRUD\AccountsController::deleteAction }
    methods: [DELETE]
