
##exchange_ticker:
##    path:  /exchange/v1/ticker/{currency}
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Exchange\PublicController::ticker }
##    methods: [GET]

##exchange_ticker_v2:
##    path:  /exchange/v2/ticker/{currency}
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Exchange\PublicController::tickerV2 }
##    methods: [GET]

##exchange_currencies:
##    path:  /exchange/v1/currencies
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Exchange\PublicController::currencies }
##    methods: [GET]
