
exchange_ticker:
    pattern:  /exchange/v1/ticker/{currency}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Exchange\PublicController::ticker }
    requirements:
        _method: GET

exchange_currencies:
    pattern:  /exchange/v1/currencies
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Exchange\PublicController::currencies }
    requirements:
        _method: GET

get_maps:
    pattern:  /maps/v1/{service}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Exchange\PublicController::maps }
    requirements:
        _method: GET
