
exchange_ticker:
    pattern:  /exchange/v1/ticker/{currency}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Exchange\PublicController::ticker }
    requirements:
        _method: GET

exchange_ticker_v2:
    pattern:  /exchange/v2/ticker/{currency}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Exchange\PublicController::tickerV2 }
    requirements:
        _method: GET

exchange_ticker_vFair:
    pattern:  /exchange/v0/ticker/{currency}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Exchange\PublicController::tickerVFair }
    requirements:
        _method: GET

exchange_currencies:
    pattern:  /exchange/v1/currencies
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Exchange\PublicController::currencies }
    requirements:
        _method: GET

get_maps:
    pattern:  /maps/v1/{service}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Exchange\PublicController::maps }
    requirements:
        _method: GET
