#################################################### REAL SERVICE CALLS ##############################################

service_call:
    pattern:  /services/v1/{service_cname}/{service_function}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\IncomingController::make, _format: ~ }
    requirements:
        _method: GET|POST
        service_cname: "[a-z0-9_]+"
        service_function: "[a-z0-9_]+"

service_call_with_id:
    pattern:  /services/v1/{service_cname}/{service_function}/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\IncomingController::make, _format: ~ }
    requirements:
        _method: GET|POST
        service_cname: "[a-z0-9_]+"
        service_function: "[a-z0-9_]+"
        id: "[a-z0-9]+"

################################################## SANDBOX SERVICE CALLS ##############################################

service_sandbox_call:
    pattern:  /sandbox/services/v1/{service_cname}/{service_function}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\IncomingController::makeTest, _format: ~ }
    requirements:
        _method: GET|POST
        service_cname: "[a-z0-9_]+"
        service_function: "[a-z0-9_]+"

service_sandbox_call_with_id:
    pattern:  /sandbox/services/v1/{service_cname}/{service_function}/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\IncomingController::makeTest, _format: ~ }
    requirements:
        _method: GET|POST
        service_cname: "[a-z0-9_]+"
        service_function: "[a-z0-9_]+"
        id: "[a-z0-9]+"

##################################################### TEST SERVICE CALLS ##############################################

service_test_call:
    pattern:  /sandbox/services/v1/{service_cname}/{service_function}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\IncomingController::makeTest, _format: ~ }
    requirements:
        _method: GET|POST
        service_cname: "[a-z0-9_]+"
        service_function: "[a-z0-9_]+"

service_test_call_with_id:
    pattern:  /sandbox/services/v1/{service_cname}/{service_function}/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\IncomingController::makeTest, _format: ~ }
    requirements:
        _method: GET|POST
        service_cname: "[a-z0-9_]+"
        service_function: "[a-z0-9_]+"
        id: "[a-z0-9]+"
