
##################### manager/users ############################

admin_users_index:
    pattern:  /manager/v1/users
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersController::indexAction, _format: ~ }
    requirements:
        _method: GET

manager_users_index_by_group:
    pattern:  /manager/v1/usersbygroup/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersController::indexByGroup, _format: ~ }
    requirements:
        _method: GET

##admin_users_set_image:
##    pattern:  /manager/v1/users/{id}/image
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersController::setImage, _format: ~ }
##    requirements:
##        _method: PUT


admin_users_read:
    pattern:  /manager/v1/users/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersController::showAction, _format: ~ }
    requirements:
        _method: GET
        id: "[0-9]+"

##admin_users_add:
##    pattern:  /manager/v1/users
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersController::createAction, _format: ~ }
##    requirements:
##        _method: POST
##        name: "string"
##        email: "email"
##        password: "string"

admin_users_update:
    pattern:  /manager/v1/users/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersController::updateAction, _format: ~ }
    requirements:
        _method: PUT
        id: "[0-9]+"
        name: "string"
        email: "email"
        password: "string"

admin_users_delete:
    pattern:  /manager/v1/users/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersController::deleteAction, _format: ~ }
    requirements:
        _method: DELETE
        id: "[0-9]+"

admin_users_delete_by_name:
    pattern:  /manager/v1/users/name/{username}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersController::deleteByNameAction, _format: ~ }
    requirements:
        _method: DELETE
        username: "string"

##manager_su:
##    pattern:  /manager/v1/su/{id}
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersController::su }
##    requirements:
##        _method: GET
##        id: "[0-9]+"

##########################    MANAGER COMPANIES     ###########################

admin_groups_index:
    pattern:  /manager/v1/groups
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\GroupsController::indexAction, _format: ~ }
    requirements:
        _method: GET

admin_groups_read:
    pattern:  /groups/v1/show/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\GroupsController::showAction, _format: ~ }
    requirements:
        _method: GET
        id: "[0-9]+"

##admin_groups_add:
##    pattern:  /manager/v1/groups
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\GroupsController::createAction, _format: ~ }
##    requirements:
##        _method: POST
##        name: "string"

admin_groups_update:
    pattern:  /manager/v1/groups/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\GroupsController::updateAction, _format: ~ }
    requirements:
        _method: PUT
        id: "[0-9]+"
        name: "string"

admin_groups_set_image:
    pattern:  /manager/v1/groups/{id}/image
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\GroupsController::setImage, _format: ~ }
    requirements:
        _method: PUT
        id: "[0-9]+"

admin_groups_update_limit:
    pattern:  /manager/v1/groups/limit/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\LimitsGroupController::updateAction, _format: ~ }
    requirements:
        _method: PUT
        id: "[0-9]+"


admin_groups_delete:
    pattern:  /manager/v1/groups/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\GroupsController::deleteAction, _format: ~ }
    requirements:
        _method: DELETE
        id: "[0-9]+"

admin_groups_add_users:
    pattern:  /manager/v1/groups/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersGroupsController::createAction, _format: ~ }
    requirements:
        _method: POST
        user_id: "[0-9]+"

##user_new_group:
##    pattern:  /user/v1/new/account
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersGroupsController::createCompanyAction, _format: ~ }
##    requirements:
##        _method: POST
##        user_id: "[0-9]+"

admin_groups_delete_users:
    pattern:  /manager/v1/groups/{group_id}/{user_id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersGroupsController::deleteAction, _format: ~ }
    requirements:
        _method: DELETE
        group_id: "[0-9]+"
        user_id: "[0-9]+"

admin_groups_add_users_role:
    pattern:  /manager/v1/groupsrole/{group_id}/{user_id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersGroupsController::addRoleAction, _format: ~ }
    requirements:
        _method: POST
        group_id: "[0-9]+"
        user_id: "[0-9]+"

admin_groups_delete_users_role:
    pattern:  /manager/v1/groupsrole/{group_id}/{user_id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersGroupsController::deleteRoleAction, _format: ~ }
    requirements:
        _method: DELETE
        group_id: "[0-9]+"
        user_id: "[0-9]+"