
##################### manager/users ############################

admin_users_index:
    pattern:  /manager/v1/users
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Manager\UsersController::indexAction, _format: ~ }
    requirements:
        _method: GET


admin_users_set_image:
    pattern:  /manager/v1/users/{id}/image
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Manager\UsersController::setImage, _format: ~ }
    requirements:
        _method: PUT


admin_users_read:
    pattern:  /manager/v1/users/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Manager\UsersController::showAction, _format: ~ }
    requirements:
        _method: GET
        id: "[0-9]+"

admin_users_add:
    pattern:  /manager/v1/users
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersController::createAction, _format: ~ }
    requirements:
        _method: POST
        name: "string"
        email: "email"
        password: "string"


admin_users_update:
    pattern:  /manager/v1/users/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersController::updateAction, _format: ~ }
    requirements:
        _method: PUT
        id: "[0-9]+"
        name: "string"
        email: "email"
        password: "string"

admin_users_delete:
    pattern:  /manager/v1/users/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersController::deleteAction, _format: ~ }
    requirements:
        _method: DELETE
        id: "[0-9]+"

admin_users_add_service:
    pattern:  /manager/v1/users/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersController::addService }
    requirements:
        _method: POST
        id: "[0-9]+"

admin_users_delete_service:
    pattern:  /manager/v1/users/{id}/{service_id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersController::deleteService }
    requirements:
        _method: DELETE
        id: "[0-9]+"
        service_id: "[0-9]+"

manager_su:
    pattern:  /manager/v1/su/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Manager\UsersController::su }
    requirements:
        _method: GET
