######################## USER POS ########################

user_POS_index:
    pattern:  /pos/v1/manager
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\POSController::indexAction }
    requirements:
        _method: GET

user_POS_index:
    pattern:  /pos/v1/manager/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\POSController::showAction }
    requirements:
        _method: GET

user_POS_create:
    pattern:  /pos/v1/manager
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\POSController::createAction }
    requirements:
        _method: POST

user_POS_update:
    pattern:  /pos/v1/manager/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\POSController::updateAction }
    requirements:
        _method: PUT

user_POS_delete:
    pattern:  /pos/v1/manager/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\POSController::deleteAction }
    requirements:
        _method: DELETE

user_POS_transaction:
    pattern:  /pos/v{version_number}/transaction/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\POSIncomingController::createTransaction }
    requirements:
        _method: POST

new_btc_address:
    pattern:  /pos/v{version_number}/address
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\POSIncomingController::generateAddress }
    requirements:
        _method: POST
