############################################### PUBLIC ENDPOINTS #######################################################

public_v1_status:
    path: /public/v1/status
    defaults: {_controller: Telepay\FinancialApiBundle\Controller\Open\StatusController::status }
    methods: [GET]

public_map_list:
    path: /public/map/v1/list
    defaults: {_controller: Telepay\FinancialApiBundle\Controller\Open\MapController::ListAction }
    methods: [GET]

public_map_search:
    path: /public/map/v1/search
    defaults: {_controller: Telepay\FinancialApiBundle\Controller\Open\MapController::SearchAction }
    methods: [GET]

public_v2_map:
    path: /public/v2/map
    defaults: {_controller: Telepay\FinancialApiBundle\Controller\Open\MapController::searchV2 }
    methods: [GET]
