
Sample:
    resource: services/sample.yml

Ukash:
    resource: services/ukash.yml

PagoFacil:
    resource: services/pagofacil.yml

PagoFacil2000charge:
    resource: services/2000chargepagofacil.yml

PaynetPay:
    resource: services/paynetpay.yml

PaynetRef:
    resource: services/paynetref.yml

PayU:
    resource: services/payu.yml

SafetyPay:
    resource: services/safetypay.yml

ToditoCash:
    resource: services/toditocash.yml

Pademobile:
    resource: services/pademobile.yml

Ukashgenerate:
    resource: services/ukashgenerate.yml

Ukashredemption:
    resource: services/ukashgenerate.yml

HalcashSend:
    resource: services/halcash.yml

HalcashPayment:
    resource: services/halcash.yml

Paysafecard:
    resource: services/paysafecard.yml

Multiva:
    resource: services/multiva.yml

Sabadell:
    resource: services/sabadell.yml