
Sample:
    resource: services/sample.yml

Ukash:
    resource: services/ukash.yml

PagoFacil:
    resource: services/pagofacil.yml

PagoFacil2000charge:
    resource: services/2000chargepagofacil.yml

PaynetPay:
    resource: services/paynetpay.yml

PaynetRef:
    resource: services/paynetref.yml

PayU:
    resource: services/payu.yml

SafetyPay:
    resource: services/safetypay.yml

ToditoCash:
    resource: services/toditocash.yml