######################## COMBO SERVICES ########################

btc_halcash:
    pattern:  /swift/v{version_number}/{type_in}/{type_out}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\SwiftController::make ,_format: ~}
    requirements:
        _method: POST
        type_in: "[a-z0-9_]+"
        type_out: "[a-z0-9_]+"

check_swift:
    pattern:  /swift/v{version_number}/{type_in}/{type_out}/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\SwiftController::check ,_format: ~}
    requirements:
        _method: GET
        type_in: "[a-z0-9_]+"
        type_out: "[a-z0-9_]+"




#service_call_create:
#    pattern:  /services/v{version_number}/{service_cname}
#    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\IncomingController::make, _format: ~ }
#    requirements:
#        _method: POST
#        service_cname: "[a-z0-9_]+"


###########################  OLD SERVICES ########################

old_btc_halcash:
    pattern:  /api/send
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\AdapterController::make ,_format: ~ ,type_in: 'btc' ,type_out: 'halcash'}
    requirements:
        _method: POST

old_btc_halcash_check:
    pattern:  /api/send/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\AdapterController::check ,_format: ~ ,type_in: 'btc' ,type_out: 'halcash', version_number: '1'}
    requirements:
        _method: GET

old_fac_halcash:
    pattern:  /api/fac/send
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\AdapterController::make ,_format: ~ ,type_in: 'fac' ,type_out: 'halcash'}
    requirements:
        _method: POST

old_btc_halcash_check:
    pattern:  /api/fac/send/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\AdapterController::check ,_format: ~ ,type_in: 'fac' ,type_out: 'halcash', version_number: '1'}
    requirements:
        _method: GET