######################## COMBO SERVICES ########################

btc_halcash:
    pattern:  /swift/v{version_number}/{type_in}/{type_out}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\SwiftController::make ,_format: ~}
    requirements:
        _method: POST
        type_in: "[a-z0-9_]+"
        type_out: "[a-z0-9_]+"


#service_call_create:
#    pattern:  /services/v{version_number}/{service_cname}
#    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Transactions\IncomingController::make, _format: ~ }
#    requirements:
#        _method: POST
#        service_cname: "[a-z0-9_]+"