######################## USER ACCOUNT ########################

user_account:
    pattern:  /user/v1/account
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::read }
    requirements:
        _method: GET

user_account_edit:
    pattern:  /user/v1/account
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::updateAction }
    requirements:
        _method: PUT

user_service_read:
    pattern:  /user/v1/services/{service}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Integrator\ServicesController::read }
    requirements:
        _method: GET

user_method_read:
    pattern:  /user/v1/methods/{method}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Integrator\MethodsController::read }
    requirements:
        _method: GET

user_method_index:
    pattern:  /user/v1/methods
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Integrator\MethodsController::index }
    requirements:
        _method: GET

user_index_companies:
    pattern:  /user/v1/companies
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::indexCompanies, _format: ~ }
    requirements:
        _method: GET


######################## USER WALLET ########################

user_wallet:
    pattern:  /user/v1/wallet
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::read }
    requirements:
        _method: GET

user_wallet_transactions:
    pattern:  /user/v1/wallet/transactions
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::walletTransactions }
    requirements:
        _method: GET

user_wallet_transactions_daily_group:
    pattern:  /user/v1/wallet/dailytransactions
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::walletDailySumTransactions }
    requirements:
        _method: GET

user_wallet_transactions_v2:
    pattern:  /user/v2/wallet/transactions
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::walletTransactionsV2 }
    requirements:
        _method: GET

user_wallet_transactions_sum:
    pattern:  /user/v1/wallet/earnings
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::benefits }
    requirements:
        _method: GET

user_wallet_transactions_sum_month:
    pattern:  /user/v1/wallet/monthearnings
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::monthBenefits }
    requirements:
        _method: GET

user_wallet_transactions_sum_country:
    pattern:  /user/v1/wallet/countryearnings
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::countryBenefits }
    requirements:
        _method: GET

user_wallet_currency_exchange:
    pattern:  /user/v1/wallet/currency_exchange
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::currencyExchange, _format: ~ }
    requirements:
        _method: POST


######################## USER ANALYTICS ########################

user_analytics:
    pattern:  /user/v1/analytics
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::analytics }
    requirements:
        _method: GET

user_set_image:
    pattern:  /user/v1/image
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::setImage }
    requirements:
        _method: PUT

user_transactions_speed:
    pattern:  /user/v1/speed
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::speed }
    requirements:
        _method: GET

user_transactions_last10:
    pattern:  /user/v1/last
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::last }
    requirements:
        _method: GET

user_transaction_single:
    pattern:  /user/v1/single/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::single }
    requirements:
        _method: GET

user_change_active_group:
    pattern:  /user/v1/activegroup
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::changeGroup }
    requirements:
        _method: PUT

user_set_default_currency:
    pattern:  /user/v1/currency
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::updateCurrency }
    requirements:
        _method: PUT

user_active_2fa:
    pattern:  /user/v1/active2fa
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::active2faAction }
    requirements:
        _method: PUT

user_deactive_2fa:
    pattern:  /user/v1/deactive2fa
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::deactive2faAction }
    requirements:
        _method: PUT

user_update_2fa_code:
    pattern:  /user/v1/update2fa
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::update2faAction }
    requirements:
        _method: PUT

user_get_exchange:
    pattern:  /user/v1/exchange
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\ExchangeController::read }
    requirements:
        _method: GET

user_transfer_wallet_to_wallet:
    pattern:  /user/v1/wallet/send/{currency}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::walletToWallet }
    requirements:
        _method: POST

user_reset_client_credentials:
    pattern:  /user/v1/reset_credentials
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::resetCredentials }
    requirements:
        _method: PUT

user_save_kyc:
    pattern:  /user/v1/save_kyc
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::kycSave }
    requirements:
        _method: POST



######################## USER BTCWALLET ########################

user_btc_wallet_read:
    pattern:  /user/v1/btc_wallet
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::read }
    requirements:
        _method: GET

user_btc_wallet_create:
    pattern:  /user/v1/btc_wallet
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::createBTCWallet }
    requirements:
        _method: POST

user_btc_wallet_update:
    pattern:  /user/v1/btc_wallet
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::updateBTCWallet }
    requirements:
        _method: PUT

user_btc_adresses_read:
    pattern:  /user/v1/btc_addresses
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::indexAction }
    requirements:
        _method: GET

user_btc_adresses_create:
    pattern:  /user/v1/btc_addresses
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::addAddress }
    requirements:
        _method: POST

user_btc_adresses_update:
    pattern:  /user/v1/btc_addresses/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::updateAddress }
    requirements:
        _method: PUT

user_devices_index:
    pattern:  /user/v1/devices
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::indexDevices }
    requirements:
        _method: GET

user_devices_create:
    pattern:  /user/v1/devices
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::addDevice }
    requirements:
        _method: POST

user_devices_update:
    pattern:  /user/v1/devices/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::updateDevice }
    requirements:
        _method: PUT

user_devices_delete:
    pattern:  /user/v1/devices/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::deleteDevice }
    requirements:
        _method: DELETE

######################## USER CASH IN TOKEN ########################

user_cash_in_create:
    pattern:  /user/v1/cash_in_token
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\CashInController::createAction }
    requirements:
        _method: POST

user_cash_in_update:
    pattern:  /user/v1/cash_in_token/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\CashInController::updateAction }
    requirements:
        _method: PUT

user_cash_in_show:
    pattern:  /user/v1/cash_in_token
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\CashInController::indexAction }
    requirements:
        _method: GET

######################## USER FEES ########################

user_fees:
    pattern:  /user/v1/fees
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::userFees }
    requirements:
        _method: GET

user_limits:
    pattern:  /user/v1/limits
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::userLimits }
    requirements:
        _method: GET

######################## USER SWIFT ########################

user_swift_clients:
    pattern:  /user/v1/swift
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\SwiftController::read }
    requirements:
        _method: GET

user_swift_list:
    pattern:  /user/v1/swift_list
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\SwiftController::listNames }
    requirements:
        _method: GET

user_swift_edit_client:
    pattern:  /user/v1/swift/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\SwiftController::updateAction }
    requirements:
        _method: PUT

user_swift_update_fees:
    pattern:  /user/v1/swift/fees/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\SwiftController::updateFees }
    requirements:
        _method: PUT

user_swift_update_transaction:
    pattern:  /user/v1/swift/transaction/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\SwiftController::updateTransaction }
    requirements:
        _method: PUT

######################## USER FEES ########################

scheduled_list:
    pattern:  /user/v1/scheduled
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\ScheduledController::indexAction }
    requirements:
        _method: GET

scheduled_create:
    pattern:  /user/v1/scheduled
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\ScheduledController::createAction }
    requirements:
        _method: POST

scheduled_update:
    pattern:  /user/v1/scheduled/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\ScheduledController::updateAction }
    requirements:
        _method: PUT

scheduled_delete:
    pattern:  /user/v1/scheduled/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\ScheduledController::deleteAction }
    requirements:
        _method: DELETE