######################## USER ACCOUNT ########################

user_account:
    pattern:  /user/v1/account
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::read }
    requirements:
        _method: GET

user_account_edit:
    pattern:  /user/v1/account
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::updateAction }
    requirements:
        _method: PUT

user_wallet:
    pattern:  /user/v1/wallet
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::read }
    requirements:
        _method: GET

user_wallet_transactions:
    pattern:  /user/v1/wallet/transactions
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::walletTransactions }
    requirements:
        _method: GET

user_wallet_transactions_sum:
    pattern:  /user/v1/wallet/earnings
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::benefits }
    requirements:
        _method: GET

user_analytics:
    pattern:  /user/v1/analytics
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::analytics }
    requirements:
        _method: GET

user_transactions_speed:
    pattern:  /user/v1/speed
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::speed }
    requirements:
        _method: GET

user_transactions_last10:
    pattern:  /user/v1/last
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::last }
    requirements:
        _method: GET

user_set_default_currency:
    pattern:  /user/v1/currency
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::updateCurrency }
    requirements:
        _method: PUT

