######################## USER ACCOUNT ########################

user_account:
    pattern:  /user/v1/account
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::read }
    requirements:
        _method: GET

user_account_edit:
    pattern:  /user/v1/account
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::updateAction }
    requirements:
        _method: PUT


######################## USER WALLET ########################

user_wallet:
    pattern:  /user/v1/wallet
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::read }
    requirements:
        _method: GET

user_wallet_transactions:
    pattern:  /user/v1/wallet/transactions
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::walletTransactions }
    requirements:
        _method: GET

user_wallet_transactions_v2:
    pattern:  /user/v2/wallet/transactions
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::walletTransactionsV2 }
    requirements:
        _method: GET

user_wallet_transactions_sum:
    pattern:  /user/v1/wallet/earnings
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::benefits }
    requirements:
        _method: GET

user_wallet_transactions_sum_month:
    pattern:  /user/v1/wallet/monthearnings
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::monthBenefits }
    requirements:
        _method: GET

user_wallet_transactions_sum_country:
    pattern:  /user/v1/wallet/countryearnings
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::countryBenefits }
    requirements:
        _method: GET


######################## USER ANALYTICS ########################

user_analytics:
    pattern:  /user/v1/analytics
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::analytics }
    requirements:
        _method: GET

user_transactions_speed:
    pattern:  /user/v1/speed
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::speed }
    requirements:
        _method: GET

user_transactions_last10:
    pattern:  /user/v1/last
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::last }
    requirements:
        _method: GET

user_set_default_currency:
    pattern:  /user/v1/currency
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::updateCurrency }
    requirements:
        _method: PUT

user_get_exchange:
    pattern:  /user/v1/exchange
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\ExchangeController::read }
    requirements:
        _method: GET

user_transfer_wallet_to_wallet:
    pattern:  /user/v1/wallet/send/{currency}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\WalletController::walletToWallet }
    requirements:
        _method: POST

user_reset_client_credentials:
    pattern:  /user/v1/reset_credentials
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\AccountController::resetCredentials }
    requirements:
        _method: PUT


######################## USER BTCWALLET ########################

user_btc_wallet_read:
    pattern:  /user/v1/btc_wallet
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::read }
    requirements:
        _method: GET

user_btc_wallet_create:
    pattern:  /user/v1/btc_wallet
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::createBTCWallet }
    requirements:
        _method: POST

user_btc_adresses_read:
    pattern:  /user/v1/btc_addresses
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::indexAction }
    requirements:
        _method: GET

user_btc_adresses_create:
    pattern:  /user/v1/btc_addresses
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::addAddress }
    requirements:
        _method: POST

user_btc_adresses_update:
    pattern:  /user/v1/btc_addresses/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::updateAddress }
    requirements:
        _method: PUT

user_devices_index:
    pattern:  /user/v1/devices
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::indexDevices }
    requirements:
        _method: GET

user_devices_create:
    pattern:  /user/v1/devices
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::addDevice }
    requirements:
        _method: POST

user_devices_update:
    pattern:  /user/v1/devices/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::updateDevice }
    requirements:
        _method: PUT

user_devices_delete:
    pattern:  /user/v1/devices/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\User\BTCWalletController::deleteDevice }
    requirements:
        _method: DELETE


