b2b_register:
    path:  /rezero_b2b/v4/register
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::registerAccountAction }
    methods: [POST]

b2b_recover_password:
    path:  /rezero_b2b/v4/recover-password
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::passwordRecoveryV4 }
    methods: [POST]

b2b_validate_phone:
    path:  /rezero_b2b/v4/validate-phone
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::validatePhoneCodeV4 }
    methods: [POST]

discourse_bridge:
    path:  /rezero_b2b/v1/bridge/{discourse_endpoint}
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\DiscourseController::bridgeDiscourseAction }
    methods: [GET, POST, PUT, DELETE]
    requirements:
        discourse_endpoint: ".+"
