######################## OFFERS ########################

create_offer_v4:
    path:  /company/v4/offers
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\OfferController::registerOfferV4 }
    methods: [POST]

index_offer_v4:
    path:  /company/v4/offers
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\OfferController::indexOffersV4 }
    methods: [GET]

update_offer_v4:
    path:  /company/v4/offers/{offer_id}
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\OfferController::updateOfferFromCompanyV4 }
    methods: [PUT]

delete_offer_v4:
    path:  /company/v4/offers/{offer_id}
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\OfferController::deleteActionV4 }
    methods: [DELETE]

##################### MAP ############################
map_search:
    path: /map/v1/search
    defaults: {_controller: App\FinancialApiBundle\Controller\Open\MapController::SearchAction }
    methods: [GET]