##################### COMPANY ACCOUNT ############################
account_update:
    path: /account/{account_id}/v1/profile
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\AccountController::updateAction }
    methods: [PUT]
    requirements:
        account_id: "[a-z0-9_]+"

fixed_location_update:
    path: /account/{account_id}/v1/location
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\AccountController::updateLocationAction }
    methods: [PUT]
    requirements:
        account_id: "[a-z0-9_]+"

######################## CREDIT CARD ########################

create_credit_card:
    path:  /company/v1/credit_card
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\CreditCardController::registerCard }
    methods: [POST]

index_credit_card:
    path:  /company/v1/credit_card
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\CreditCardController::indexCards }
    methods: [GET]

update_credit_card:
    path:  /company/v1/credit_card/{id}
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\CreditCardController::updateCardFromCompany }
    methods: [PUT]

delete_credit_card:
    path:  /company/v1/credit_card/{id}
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\CreditCardController::deleteAction }
    methods: [DELETE]

######################## BANK ACCOUNT ########################

create_bank_account:
    path:  /company/v1/bank_account
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\BankAccountController::registerAccount }
    methods: [POST]

index_bank_account:
    path:  /company/v1/bank_account
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\BankAccountController::indexAccounts }
    methods: [GET]

update_bank_account:
    path:  /company/v1/bank_account/{id}
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\BankAccountController::updateAccountFromCompany }
    methods: [PUT]

delete_bank_account:
    path:  /company/v1/bank_account/{id}
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\BankAccountController::deleteAction }
    methods: [DELETE]


######################## OFFERS ########################

create_offer:
    path:  /company/v1/offer
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\OfferController::registerOffer }
    methods: [POST]

index_offer:
    path:  /company/v1/offer
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\OfferController::indexOffers }
    methods: [GET]

update_offer:
    path:  /company/v1/offer/{id}
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\OfferController::updateOfferFromCompany }
    methods: [PUT]

delete_offer:
    path:  /company/v1/offer/{id}
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\OfferController::deleteAction }
    methods: [DELETE]

######################## Products ########################

list_all_categories:
    path:  /company/v1/list_categories
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\ProductController::listAllAction }
    methods: [GET]

index_products:
    path:  /company/v1/products
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\ProductController::indexAction }
    methods: [GET]

set_products:
    path:  /company/v1/products
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\ProductController::setAction }
    methods: [PUT]

set_category:
    path:  /company/v1/category
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\ProductController::setCategoryAction }
    methods: [PUT]

###################   COMPANY WALLET #################
company_wallet:
    path:  /company/{company_id}/v1/wallets
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\WalletController::read }
    methods: [GET]

##company_wallet_do_exchange:
##    path:  /company/{company_id}/v1/wallet/exchange
##    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\WalletController::currencyExchange, _format: ~ }
##    methods: [POST]

company_wallet_transactions:
    path:  /company/{company_id}/v1/wallet/transactions
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\WalletController::walletTransactions }
    methods: [GET]

###################   COMPANY SETTINGS #################
##company_read_settings:
##    path: /company/v1/{company_id}/settings
##    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\SettingsController::readSettings }
##    methods: [GET]

##company_update_settings:
##    path: /company/v1/{company_id}/settings
##    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Company\SettingsController::updateSettings }
##    methods: [PUT]

##################     COMPANY METHODS     ###############
##companymethod_read:
##    path:  /company/{id}/v1/methods/{method}
##    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Integrator\MethodsController::read }
##    methods: [GET]

##companymethod_index:
##    path:  /company/{id}/v1/methods
##    defaults: { _controller: App\FinancialApiBundle\Controller\Management\Integrator\MethodsController::index }
##    methods: [GET]


#################     ACCOUNT FEES    ######################
##company_index_fees:
##    path: /account/{account_id}/v1/fees
##    defaults: {_controller: App\FinancialApiBundle\Controller\Management\Company\WalletController::indexFees }
##    requirements:
##    methods: [GET]

##company_show_fee:
##    path: /account/{account_id}/v1/fees/{method}
##    defaults: {_controller: App\FinancialApiBundle\Controller\Management\Company\WalletController::showFees }
##    requirements:
##    methods: [GET]


##################### MAP ############################
map_list:
    path: /map/v1/list
    defaults: {_controller: App\FinancialApiBundle\Controller\Open\MapController::ListAction }
    methods: [GET]

map_search:
    path: /map/v1/search
    defaults: {_controller: App\FinancialApiBundle\Controller\Open\MapController::SearchAction }
    methods: [GET]

