############################################### PUBLIC ENDPOINTS #######################################################

public_v1_status:
    path: /public/v1/status
    defaults: {_controller: App\FinancialApiBundle\Controller\Open\StatusController::status }
    methods: [GET]

public_v1_info:
    path: /public/v1/info
    defaults: {_controller: App\FinancialApiBundle\Controller\Open\StatusController::info }
    methods: [GET]

public_v1_webhook_mailgun:
    path: /public/v3/webhooks/mailgun
    defaults: {_controller: App\FinancialApiBundle\Controller\Open\MailgunController::webhookAction }
    methods: [POST]

public_map_search:
    path: /public/map/v1/search
    defaults: {_controller: App\FinancialApiBundle\Controller\Open\MapController::SearchAction }
    methods: [GET]
