#################################################### REAL SERVICE CALLS ##############################################

method_call_createV2:
    path:  /methods/v3/{type}/{method_cname}
    defaults: { _controller: App\FinancialApiBundle\Controller\Transactions\IncomingController3::make, _format: ~ }
    methods: [POST]

method_call_create:
    path:  /methods/v{version_number}/{type}/{method_cname}
    defaults: { _controller: App\FinancialApiBundle\Controller\Transactions\IncomingController2::make, _format: ~ }
    methods: [POST]
    requirements:
        service_cname: "[a-z0-9_]+"

method_delegated_create:
    path:  /delegated/{method_cname}
    defaults: { _controller: App\FinancialApiBundle\Controller\Transactions\IncomingController2::remoteDelegatedTransaction, _format: ~ }
    methods: [POST]
    requirements:
        service_cname: "[a-z0-9_]+"

method_admin_third_create3:
    path:  /admin/v3/third/{method_cname}
    defaults: { _controller: App\FinancialApiBundle\Controller\Transactions\IncomingController3::adminThirdTransaction, _format: ~ }
    methods: [POST]
    requirements:
        service_cname: "[a-z0-9_]+"

method_admin_third_create:
    path:  /admin/v{version_number}/third/{method_cname}
    defaults: { _controller: App\FinancialApiBundle\Controller\Transactions\IncomingController2::adminThirdTransaction, _format: ~ }
    methods: [POST]
    requirements:
        service_cname: "[a-z0-9_]+"

method_call_update:
    path:  /methods/v{version_number}/{type}/{method_cname}/{id}
    defaults: { _controller: App\FinancialApiBundle\Controller\Transactions\IncomingController2::update, _format: ~ }
    methods: [PUT]
    requirements:
        service_cname: "[a-z0-9_]+"
        id: "[a-z0-9]+"

method_call_find:
    path:  /methods/v{version_number}/{type}/{method_cname}
    defaults: { _controller: App\FinancialApiBundle\Controller\Transactions\IncomingController2::find, _format: ~ }
    methods: [GET]
    requirements:
        service_cname: "[a-z0-9_]+"

vendor_data_get:
    path:  /transaction/v{version_number}/vendor
    defaults: { _controller: App\FinancialApiBundle\Controller\Transactions\IncomingController2::checkReceiverData, _format: ~ }
    methods: [GET]


sender_data_get:
    path:  /transaction/v{version_number}/customer
    defaults: { _controller: App\FinancialApiBundle\Controller\Transactions\IncomingController2::checkSenderData, _format: ~ }
    methods: [GET]

method_call_check:
    path:  /methods/v{version_number}/{type}/{method_cname}/{id}
    defaults: { _controller: App\FinancialApiBundle\Controller\Transactions\IncomingController2::check, _format: ~ }
    methods: [GET]
    requirements:
        service_cname: "[a-z0-9_]+"
        id: "[a-z0-9]+"

service_notificate:
    path:  /notifications/v{version_number}/{service_cname}/{status}
    defaults: { _controller: App\FinancialApiBundle\Controller\Transactions\NotificationsController::notificate, _format: ~ }
    methods: [POST]
    requirements:
        service_cname: "[a-z0-9_]+"
        id: "[a-z0-9]+"

service_notificate_get:
    path:  /notifications/v{version_number}/{service_cname}/{status}
    defaults: { _controller: App\FinancialApiBundle\Controller\Transactions\NotificationsController::notificateGET, _format: ~ }
    methods: [GET]
    requirements:
        service_cname: "[a-z0-9_]+"
        id: "[a-z0-9]+"
