######################## USER ACCOUNT ########################

user_account:
    path:  /user/v1/account
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::read }
    methods: [GET]

user_account_edit:
    path:  /user/v1/account
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::updateAction }
    methods: [PUT]

user_tos_edit:
    path:  /user/v4/campaign/accept_tos
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::updateV4Action }
    methods: [PUT]

user_index_companies:
    path:  /user/v1/companies
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::indexCompanies, _format: ~ }
    methods: [GET]

user_account_resume:
    path:  /user/v1/account/resume
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::resume }
    methods: [GET]

######################## USER WALLET ########################


commerce_list_exchangers_old:
    path:  /user/v1/wallet/listCommerce
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\WalletController::listCommerce }
    methods: [GET]

commerce_list_exchangers:
    path:  /user/v1/wallet/exchangers
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\WalletController::listCommerce }
    methods: [GET]

company_wallet_day_transactions:
    path:  /user/v1/wallet/day/transactions
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\WalletController::walletDayTransactions }
    methods: [GET]

user_wallet_transactions_v2:
    path:  /user/v2/wallet/transactions
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\WalletController::walletTransactionsV2 }
    methods: [GET]

######################## USER ANALYTICS ########################

user_transactions_last10:
    path:  /user/v1/last
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\WalletController::last }
    methods: [GET]

user_transactions_day_sum:
    path:  /user/v1/day
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\WalletController::day }
    methods: [GET]

user_change_active_group:
    path:  /user/v1/activegroup
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::changeGroup }
    methods: [PUT]

user_set_default_currency:
    path:  /user/v1/currency
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::updateCurrency }
    methods: [PUT]

user_active_2fa:
    path:  /user/v1/active2fa
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::active2faAction }
    methods: [PUT]

user_deactive_2fa:
    path:  /user/v1/deactive2fa
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::deactive2faAction }
    methods: [PUT]

user_update_public_phone:
    path:  /user/v1/public_phone
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::publicPhoneAction }
    methods: [PUT]

user_public_phone_list:
    path:  /user/v1/public_phone_list
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::publicPhoneListAction }
    methods: [POST]

user_update_2fa_code:
    path:  /user/v1/update2fa
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::update2faAction }
    methods: [PUT]

user_get_question:
    path:  /user/v1/question
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::showQuestion }
    methods: [GET]

user_change_pin:
    path:  /user/v1/pin
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::updatePin }
    methods: [POST]

user_reset_client_credentials:
    path:  /user/v1/reset_credentials
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::resetCredentials }
    methods: [PUT]

user_save_kyc:
    path:  /user/v1/save_kyc
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::kycSave }
    methods: [POST]

user_upload_file:
    path:  /user/v1/upload_file
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\UploadController::uploadFile }
    methods: [POST]

user_upload_base64:
    path:  /user/v1/upload_bas64
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\UploadController::uploadFileBase64 }
    methods: [POST]

######################## USER SECURITY ########################

user_change_passwordV4:
    path:  /user/v4/users/security/change-password
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::changePasswordV4 }
    methods: [PUT]

user_change_pinV4:
    path:  /user/v4/users/security/change-pin
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::changePinV4 }
    methods: [PUT]

user_documents_list:
    path:  /user/v4/documents
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::getDocumentsV4 }
    methods: [GET]

user_documents_post:
    path:  /user/v4/documents
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::addDocumentsV4 }
    methods: [POST]

user_documents_update:
    path:  /user/v4/documents/{doc_id}
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::updateDocumentsV4 }
    methods: [PUT]