<?php

declare(strict_types=1);

namespace App\Migrations;

use App\Entity\Award;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220706115746 extends AbstractMigration
{
    public function getDescription() : string
    {
        return 'Scoring and awards tables';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE AccountAwardItem (id INT AUTO_INCREMENT NOT NULL, account_award_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, score INT NOT NULL, topic_id INT DEFAULT NULL, post_id INT DEFAULT NULL, user_id INT DEFAULT NULL, action VARCHAR(255) NOT NULL, category INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, INDEX IDX_51B028E2459C6079 (account_award_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE AwardScoreRule (id INT AUTO_INCREMENT NOT NULL, award_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, score INT NOT NULL, action VARCHAR(255) NOT NULL, category INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, INDEX IDX_BFEC143D3D5282CF (award_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE AccountAwardItem ADD CONSTRAINT FK_51B028E2459C6079 FOREIGN KEY (account_award_id) REFERENCES AccountAward (id)');
        $this->addSql('ALTER TABLE AwardScoreRule ADD CONSTRAINT FK_BFEC143D3D5282CF FOREIGN KEY (award_id) REFERENCES Award (id)');
        $this->addSql('ALTER TABLE Award ADD thresholds LONGTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\', DROP golden_threshold, DROP silver_threshold, DROP bronze_threshold');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE AccountAwardItem');
        $this->addSql('DROP TABLE AwardScoreRule');
        $this->addSql('ALTER TABLE Award DROP thresholds');
    }

    public function postUp(Schema $schema): void
    {
        $thresholds = implode(',',[0,100,500,1500]);
        $this->insertAwards('Word', 'Palabra', 'Paraula', $thresholds);
        $this->insertAwards('Wisdom', 'Sabiduría', 'Saviesa', $thresholds);
        $this->insertAwards('Momentum', 'Impulso', "Impuls", $thresholds);
        parent::postUp($schema); // TODO: Change the autogenerated stub
    }

    private function insertAwards($name, $name_es, $name_ca, $thresholds){
        $date = new \DateTime();
        $this->connection->insert('Award', array(
            'name' => $name,
            'name_es' => $name_es,
            'name_ca' => $name_ca,
            'created' => $date->format('Y-m-d H:i:s'),
            'updated' => $date->format('Y-m-d H:i:s'),
            'thresholds' => $thresholds
        ));
    }
}
