services:

#SWIFT CONFIGURATION ONLY WITH THE OUT METHOD
#fixed, variable, min_value, max_value, range, countries

    net.app.config.btc:
        class: App\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "6"
            - "10000"
            - "100000000"
            - "10000000"
            - "All over the world"

    net.app.config.sepa:
        class: App\FinancialApiBundle\Financial\Methods\MethodConfiguration
        arguments:
            - "0"
            - "1"
            - "5000"
            - "300000"
            - "5000"
            - "All over the world"


#POS CONFIGURATIONS
#$type, $currency, $default_currency, $allowed_currencies_in, $allowed_currencies_out

    net.app.config.pos_pnp:
        class: App\FinancialApiBundle\Financial\Methods\POSConfiguration
        arguments:
            - "pos_pnp"
            - "EUR"
            - "EUR"
            - "EUR"
            - "EUR/MXN/USD/PLN/FAC/BTC"

    net.app.config.pos_btc:
        class: App\FinancialApiBundle\Financial\Methods\POSConfiguration
        arguments:
            - "pos_btc"
            - "BTC"
            - "BTC"
            - "EUR/MXN/USD/PLN/FAC/BTC"
            - "EUR/MXN/USD/PLN/FAC/BTC"

    net.app.config.pos_sabadell:
        class: App\FinancialApiBundle\Financial\Methods\POSConfiguration
        arguments:
            - "pos_sabadell"
            - "EUR"
            - "EUR"
            - "EUR/MXN/USD/PLN/FAC/BTC"
            - "EUR/MXN/USD/PLN/FAC/BTC"