services:


    net.app.provider.rec:
        class: App\FinancialApiBundle\DependencyInjection\App\Providers\EasyBitcoin
        arguments:
            - "%rec_user%"
            - "%rec_pass%"
            - "%rec_host%"
            - "%rec_port%"

    net.app.provider.sepa_in:
        class: App\FinancialApiBundle\DependencyInjection\Transactions\Libs\SepaIn
        arguments:

    net.app.provider.sepa_out:
        class: App\FinancialApiBundle\DependencyInjection\Transactions\Libs\SepaOut
        arguments:
