services:
    com.qbitartifacts.rec.commons.notificator:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\NotificatorAggregator
        arguments:
            - '@com.qbitartifacts.rec.commons.telegram_notificator_error'
            - '@com.qbitartifacts.rec.commons.telegram_notificator_log'

    com.qbitartifacts.rec.commons.telegram_notificator_error:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\TelegramNotificator
        arguments:
            - "%telegram_chat_error%"
            - "%telegram_bot_token%"

    com.qbitartifacts.rec.commons.telegram_notificator_log:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\TelegramNotificator
        arguments:
            - "%telegram_chat_log%"
            - "%telegram_bot_token%"

    net.app.commons.method_manipulator:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\MethodManipulator

    net.app.commons.fee_deal:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\FeeDeal
        arguments:
            - "@doctrine"
            - "@doctrine_mongodb"
            - "@net.app.commons.balance_manipulator"
            - "@service_container"

    net.app.commons.balance_manipulator:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\BalanceManipulator
        arguments:
            - "@doctrine"

    net.app.commons.transaction_flow_handler:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\TransactionFlowHandler
        arguments:
            - "@doctrine_mongodb"
            - "@doctrine"
            - "@net.app.commons.balance_manipulator"

    net.app.commons.bonus_handler:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\BonusHandler
        arguments:
            - "@doctrine"
            - "@net.app.commons.transaction_flow_handler"
            - "@bonissim_service"
            - "@bonus.logger"

    net.app.commons.qualification_handler:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\QualificationHandler
        arguments:
            - "@doctrine"
            - "@service_container"

    net.app.commons.shop_badge_handler:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\ShopBadgeHandler
        arguments:
            - "@doctrine"
            - "@badges.logger"

    net.app.commons.garden_handler:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\GardenHandler
        arguments:
            - "@doctrine"

    net.app.commons.campaign_checker:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\CampaignChecker
        arguments:
            - "@doctrine"
            - "@service_container"

    net.app.commons.user_checker:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\UserChecker
        arguments:
            - "@service_container"

    net.app.commons.tx_block_validator:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\TxBlockValidator
        arguments:
            - "@service_container"
            - "@transaction.logger"

    net.app.commons.tx_block_log_handler:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\TxBlockLogHandler
        arguments:
            - "@service_container"

    net.app.commons.fee_manipulator:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\FeeManipulator
        arguments:
            - "@doctrine"

    net.app.commons.limit_manipulator:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\LimitManipulator
        arguments:
            - "@doctrine"
            - "@service_container"
            - "@doctrine_mongodb"

    net.app.commons.exchange_manipulator:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\ExchangeManipulator
        arguments:
            - "@doctrine"
            - "@service_container"

    net.app.commons.permissions_checker:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\PermissionsHandler
        arguments:
            - "@service_container"
            - "@doctrine"
            - "@doctrine_mongodb"

    net.app.commons.discourse.api_manager:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\DiscourseApiManager
        arguments:
            - "@service_container"
            - "@discourse.logger"

    net.app.commons.web3.api_manager:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\Web3ApiManager
        arguments:
            - "@service_container"
            - "@discourse.logger"

    net.app.commons.award_handler:
        class: App\FinancialApiBundle\DependencyInjection\App\Commons\AwardHandler
        arguments:
            - "@doctrine"
            - "@service_container"
            - "@discourse.logger"

    net.app.transactions.core.utils:
        class: App\FinancialApiBundle\DependencyInjection\Transactions\Core\TransactionUtils
        arguments:
            - "@service_container"
            - "@doctrine"
            - "@doctrine_mongodb"
