
Admin:
    resource: routing/admin.yml

Manager:
    resource: routing/manager.yml

Company:
    resource: routing/company.yml

User:
    resource: routing/user.yml

Transactions:
    resource: routing/transactions.yml

Public:
    resource: routing/public.yml

CRUD:
    resource: routing/crud.yml

App:
    resource: routing/app.yml

validate_email:
    path:  /register/v1/validate_email
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::validateEmail }
    methods: [POST]

register_from_shop:
    path:  /register/v1/commerce/{type}
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::registerCommerceAction }
    methods: [POST]

recover_password_request:
    path:  /password_recovery/v1/request
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::passwordRecoveryRequest }
    methods: [POST]

recover_password:
    path:  /password_recovery/v1
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::passwordRecovery }
    methods: [POST]

change_pin_request:
    path:  /user/v4/users/security/sms-code/change-pin
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::changePinRequest }
    methods: [POST]

change_password_request:
    path:  /user/v4/users/security/sms-code/change-password
    defaults: { _controller: App\FinancialApiBundle\Controller\Management\User\AccountController::changePasswordRequest }
    methods: [POST]