services:
    app.is_commerce_validator:
        class: App\FinancialApiBundle\Validator\Constraint\IsCommerceValidator
        tags:
            - { name: validator.constraint_validator}

    app.is_user_validator:
        class: App\FinancialApiBundle\Validator\Constraint\IsUserValidator
        tags:
            - { name: validator.constraint_validator}

    app.is_not_expired_validator:
        class: App\FinancialApiBundle\Validator\Constraint\IsNotExpiredValidator
        tags:
            - { name: validator.constraint_validator}