name: Coverage > 20%

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v1

      - name: Running test suite
        run: test `make coverage | tail +2` -ge 20
