name: CI

on:
  push:
    branches:
      - master
      - stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build All
        env:
          REGISTRY: reg.rallf.com:8443
        run: |
          make build DOCKER_REGISTRY=${REGISTRY} DOCKER_IMAGE=rec-api DOCKER_TAG=`cut -d/ -f3 <<<${GITHUB_REF}` DOCKERFILE_DIR=docker/prod/api
          make build DOCKER_REGISTRY=${REGISTRY} DOCKER_IMAGE=rec-cron DOCKER_TAG=`cut -d/ -f3 <<<${GITHUB_REF}` DOCKERFILE_DIR=docker/prod/cron
          make build DOCKER_REGISTRY=${REGISTRY} DOCKER_IMAGE=rec-dev DOCKER_TAG=`cut -d/ -f3 <<<${GITHUB_REF}` BUILD_DIR=docs
      
      - name: Registry Login
        env:
          REGISTRY: reg.rallf.com:8443
          USERNAME: ${{ secrets.registry_username }}
          PASSWORD: ${{ secrets.registry_password }}
        run: make login DOCKER_REGISTRY=${REGISTRY} DOCKER_USERNAME=${USERNAME} DOCKER_PASSWORD=${PASSWORD}
        
      - name: Push All
        env:
          REGISTRY: reg.rallf.com:8443
        run: |
          make push DOCKER_REGISTRY=${REGISTRY} DOCKER_IMAGE=rec-api DOCKER_TAG=`cut -d/ -f3 <<<${GITHUB_REF}`
          make push DOCKER_REGISTRY=${REGISTRY} DOCKER_IMAGE=rec-cron DOCKER_TAG=`cut -d/ -f3 <<<${GITHUB_REF}`
          make push DOCKER_REGISTRY=${REGISTRY} DOCKER_IMAGE=rec-dev DOCKER_TAG=`cut -d/ -f3 <<<${GITHUB_REF}`
