name: Test and Deploy to STAGE

on:
  push:
    branches:
      - master
      - stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v1

      - name: Running test suite
        run: make test

      - name: Building the docker images
        env:
          REGISTRY: reg.rallf.com:8443
        run: |
          make build DOCKER_REGISTRY=${REGISTRY} DOCKER_IMAGE=rec-api DOCKER_TAG=`cut -d/ -f3 <<<${GITHUB_REF}` DOCKERFILE_DIR=docker/prod/api
          make build DOCKER_REGISTRY=${REGISTRY} DOCKER_IMAGE=rec-cron DOCKER_TAG=`cut -d/ -f3 <<<${GITHUB_REF}` DOCKERFILE_DIR=docker/prod/cron
          make build DOCKER_REGISTRY=${REGISTRY} DOCKER_IMAGE=rec-dev DOCKER_TAG=`cut -d/ -f3 <<<${GITHUB_REF}` BUILD_DIR=docs

      - name: Login into the registry
        env:
          REGISTRY: reg.rallf.com:8443
          USER: ${{secrets.DOCKER_USERNAME}}
          PASS: ${{secrets.DOCKER_PASSWORD}}
        run: make login DOCKER_REGISTRY=${REGISTRY} DOCKER_USERNAME=${USER} DOCKER_PASSWORD=${PASS}

      - name: Pushing images to the registry
        env:
          DOCKER_REGISTRY_URL: reg.rallf.com:8443
        run: |
          make push DOCKER_REGISTRY=${DOCKER_REGISTRY_URL} DOCKER_IMAGE=rec-api DOCKER_TAG=`cut -d/ -f3 <<<${GITHUB_REF}`
          make push DOCKER_REGISTRY=${DOCKER_REGISTRY_URL} DOCKER_IMAGE=rec-cron DOCKER_TAG=`cut -d/ -f3 <<<${GITHUB_REF}`
          make push DOCKER_REGISTRY=${DOCKER_REGISTRY_URL} DOCKER_IMAGE=rec-dev DOCKER_TAG=`cut -d/ -f3 <<<${GITHUB_REF}`

      - name: Deploying to staging server
        env:
          WEBHOOK: ${{secrets.WEBHOOK}}
        run: make deploy WEBHOOK=${WEBHOOK}
