name: Build and Deploy [PROD]

on:
  create:
    tags:

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v1

      - name: Building the docker images
        env:
          REGISTRY: reg.rallf.com:8443
        run: make build DOCKER_REGISTRY=${REGISTRY} DOCKER_IMAGE=rec-api DOCKER_TAG=stable DOCKERFILE_DIR=docker/prod/api

      - name: Login into the registry
        env:
          REGISTRY: reg.rallf.com:8443
          USER: ${{secrets.DOCKER_USERNAME}}
          PASS: ${{secrets.DOCKER_PASSWORD}}
        run: make login DOCKER_REGISTRY=${REGISTRY} DOCKER_USERNAME=${USER} DOCKER_PASSWORD=${PASS}

      - name: Pushing images to the registry
        env:
          DOCKER_REGISTRY_URL: reg.rallf.com:8443
        run: make push DOCKER_REGISTRY=${DOCKER_REGISTRY_URL} DOCKER_IMAGE=rec-api DOCKER_TAG=stable

      - name: Deploy
        uses: joelwmale/webhook-action@1.0.1
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_API_RELEASE }}
          data: "ignored"

  build-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v1

      - name: Building the docker images
        env:
          REGISTRY: reg.rallf.com:8443
        run: make build DOCKER_REGISTRY=${REGISTRY} DOCKER_IMAGE=rec-cron DOCKER_TAG=stable DOCKERFILE_DIR=docker/prod/cron

      - name: Login into the registry
        env:
          REGISTRY: reg.rallf.com:8443
          USER: ${{secrets.DOCKER_USERNAME}}
          PASS: ${{secrets.DOCKER_PASSWORD}}
        run: make login DOCKER_REGISTRY=${REGISTRY} DOCKER_USERNAME=${USER} DOCKER_PASSWORD=${PASS}

      - name: Pushing images to the registry
        env:
          DOCKER_REGISTRY_URL: reg.rallf.com:8443
        run: make push DOCKER_REGISTRY=${DOCKER_REGISTRY_URL} DOCKER_IMAGE=rec-cron DOCKER_TAG=stable

      - name: Deploy
        uses: joelwmale/webhook-action@1.0.1
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_CRON_RELEASE }}
          data: "ignored"

  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v1

      - name: Building the docker images
        env:
          REGISTRY: reg.rallf.com:8443
        run: make build DOCKER_REGISTRY=${REGISTRY} DOCKER_IMAGE=rec-dev DOCKER_TAG=stable BUILD_DIR=docs

      - name: Login into the registry
        env:
          REGISTRY: reg.rallf.com:8443
          USER: ${{secrets.DOCKER_USERNAME}}
          PASS: ${{secrets.DOCKER_PASSWORD}}
        run: make login DOCKER_REGISTRY=${REGISTRY} DOCKER_USERNAME=${USER} DOCKER_PASSWORD=${PASS}

      - name: Pushing images to the registry
        env:
          DOCKER_REGISTRY_URL: reg.rallf.com:8443
        run: make push DOCKER_REGISTRY=${DOCKER_REGISTRY_URL} DOCKER_IMAGE=rec-dev DOCKER_TAG=stable

      - name: Deploy
        uses: joelwmale/webhook-action@1.0.1
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_DEV_RELEASE }}
          data: "ignored"